/** الذكاء الاصطناعي — Artificial Intelligence. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const ai: BankQuestion[] = [
  { ar: "ماذا تعني «AI»؟", en: "What does AI stand for?", o: ["الإنترنت المتقدم", "الذكاء الاصطناعي", "واجهة التطبيق", "تحليل المعلومات"], c: 1, d: 'EASY' },
  { ar: "أي مما يلي مساعد صوتي ذكي؟", en: "Which is a voice assistant?", o: ["سيري", "فوتوشوب", "إكسل", "كروم"], c: 0, d: 'EASY' },
  { ar: "ما المجال الذي يتعلم فيه الحاسب من البيانات؟", en: "Computers learning from data is called?", o: ["تعلّم الآلة", "كتابة المقالات", "تصميم المواقع", "الشبكات"], c: 0 },
  { ar: "أي شركة طوّرت نموذج «Claude» للذكاء الاصطناعي؟", en: "Who built \"Claude\"?", o: ["جوجل", "Anthropic", "ميتا", "أمازون"], c: 1, d: 'HARD' },
  { ar: "ما اسم تقنية توليد الصور من النص؟", en: "Text-to-image generation?", o: ["الواقع المعزز", "توليد الصور", "البلوك تشين", "الحوسبة السحابية"], c: 1 },
  { ar: "ما النموذج الذي يولّد نصوصاً بشرية ويُسمى نموذجاً لغوياً كبيراً؟", en: "A \"large language model\" is abbreviated as?", o: ["CPU", "LLM", "HTML", "VPN"], c: 1, d: 'HARD' },
  { ar: "ما اسم نموذج الذكاء الاصطناعي من جوجل؟", en: "Google's AI model?", o: ["Claude", "ChatGPT", "Gemini", "Llama"], c: 2, d: 'HARD' },
  { ar: "ما اسم نموذج الذكاء الاصطناعي مفتوح المصدر من ميتا؟", en: "Meta's open-source AI model?", o: ["Claude", "Gemini", "Llama", "Grok"], c: 2, d: 'HARD' },
  { ar: "ماذا تعني «ML»؟", en: "What does ML stand for?", o: ["تعلّم الآلة", "لغة الآلة", "ذاكرة كبيرة", "شبكة محلية"], c: 0, d: 'HARD' },
  { ar: "أي مساعد صوتي ذكي من أمازون؟", en: "Amazon's voice assistant?", o: ["سيري", "أليكسا", "كورتانا", "بكسبي"], c: 1 },
  { ar: "أي مساعد صوتي ذكي من أبل؟", en: "Apple's voice assistant?", o: ["أليكسا", "سيري", "كورتانا", "جوجل أسستنت"], c: 1, d: 'EASY' },
  { ar: "ما المجال الذي يمكّن الحاسب من فهم اللغة البشرية؟", en: "Field enabling computers to understand language?", o: ["الرؤية الحاسوبية", "معالجة اللغة الطبيعية", "التعلم العميق", "البيانات الضخمة"], c: 1, d: 'HARD' },
  { ar: "ما المجال الذي يمكّن الحاسب من «رؤية» الصور وتحليلها؟", en: "Field letting computers \"see\" images?", o: ["معالجة اللغة", "الرؤية الحاسوبية", "التشفير", "الشبكات"], c: 1, d: 'HARD' },
  { ar: "ما المصطلح عندما يولّد الذكاء الاصطناعي معلومة خاطئة بثقة؟", en: "AI confidently producing false info is called?", o: ["الهلوسة", "التحيّز", "التشفير", "الفلترة"], c: 0, d: 'HARD' },
  { ar: "ما الأداة التي تولّد صوراً فنية من وصف نصي وطوّرتها OpenAI؟", en: "OpenAI's text-to-image tool?", o: ["Photoshop", "DALL·E", "Excel", "Chrome"], c: 1, d: 'HARD' },
  { ar: "ما اختصار «الذكاء الاصطناعي العام» الذي يضاهي ذكاء الإنسان؟", en: "Abbreviation for human-level general AI?", o: ["API", "AGI", "GPU", "RAM"], c: 1, d: 'HARD' },
  { ar: "ما الشركة التي طوّرت سلسلة نماذج «GPT»؟", en: "Company behind the GPT models?", o: ["جوجل", "OpenAI", "ميتا", "أبل"], c: 1 },
  { ar: "ما العتاد الأكثر استخداماً لتدريب نماذج الذكاء الاصطناعي؟", en: "Hardware most used to train AI models?", o: ["الطابعة", "كرت الرسوميات (GPU)", "الماسح", "الراوتر"], c: 1, d: 'HARD' },
  { ar: "ما المساعد الذكي من مايكروسوفت لمساعدة المبرمجين؟", en: "Microsoft's AI coding assistant?", o: ["Siri", "Copilot", "Alexa", "Bard"], c: 1, d: 'HARD' },
  { ar: "ما التقنية التي تحوّل الكلام المنطوق إلى نص؟", en: "Tech converting speech to text?", o: ["تحويل النص إلى كلام", "تحويل الكلام إلى نص", "الترجمة", "التشفير"], c: 1 },
  { ar: "ما المركبات التي تقود نفسها بالاعتماد على الذكاء الاصطناعي؟", en: "AI-driven self-operating vehicles?", o: ["الدراجات", "السيارات ذاتية القيادة", "القطارات البخارية", "الطائرات الورقية"], c: 1 },
  { ar: "ما الاسم العام للبرامج التي تحاكي محادثة الإنسان؟", en: "General name for conversation-simulating programs?", o: ["محركات البحث", "روبوتات الدردشة", "المتصفحات", "الجداول"], c: 1 },
  { ar: "ما المصطلح لميل النموذج لإعطاء نتائج منحازة بسبب بيانات التدريب؟", en: "Skewed AI results from training data are called?", o: ["الهلوسة", "التحيّز", "التشفير", "الفلترة"], c: 1, d: 'HARD' },
  { ar: "أي تطبيق ترجمة يعتمد على الذكاء الاصطناعي من جوجل؟", en: "Google's AI translation app?", o: ["ترجمة جوجل", "جيميل", "خرائط جوجل", "جوجل درايف"], c: 0, d: 'EASY' },
  { ar: "ما العملية التي «يتعلم» فيها النموذج من كميات كبيرة من البيانات؟", en: "Process where a model learns from large data?", o: ["الطباعة", "التدريب", "التشفير", "الضغط"], c: 1 },
  { ar: "ما المصطلح المرتبط بالشبكات العصبية متعددة الطبقات؟", en: "Term for multi-layer neural networks?", o: ["Deep Learning", "Big Data", "Cloud", "VPN"], c: 0, d: 'HARD' },
  { ar: "أي مجال يستخدم الذكاء الاصطناعي لتشخيص الأمراض من الصور؟", en: "Field using AI to diagnose from images?", o: ["الزراعة", "الطب", "الرياضة", "الطبخ"], c: 1 },
  { ar: "ما اسم نموذج الذكاء الاصطناعي من شركة xAI؟", en: "xAI's chatbot model?", o: ["Bard", "Grok", "Claude", "Llama"], c: 1, d: 'HARD' },
  { ar: "ما المنصة الشهيرة بتوليد الصور الفنية من النص؟", en: "Popular AI art-from-text platform?", o: ["Midjourney", "Photoshop", "Canva", "Figma"], c: 0, d: 'HARD' },
  { ar: "ما الفرق الأساسي بين الروبوت والذكاء الاصطناعي؟", en: "Key difference between a robot and AI?", o: ["لا فرق", "الروبوت آلة والذكاء برمجيات", "كلاهما برمجيات", "كلاهما عتاد"], c: 1, d: 'HARD' },
  { ar: "ما الذي يحتاجه الذكاء الاصطناعي أساساً ليتعلم؟", en: "What does AI mainly need to learn?", o: ["كهرباء فقط", "بيانات وأمثلة كثيرة", "ورق", "إنترنت فقط"], c: 1, d: 'EASY' },
  { ar: "ما المصطلح الذي يعني «واجهة برمجة التطبيقات» للتواصل بين البرامج؟", en: "Term for software-to-software interface?", o: ["CPU", "API", "GPU", "URL"], c: 1, d: 'HARD' },
  { ar: "أي مما يلي شركة متخصصة في الذكاء الاصطناعي؟", en: "Which is an AI company?", o: ["نايكي", "OpenAI", "أديداس", "زارا"], c: 1, d: 'EASY' },
  { ar: "ما الهدف العام من الذكاء الاصطناعي؟", en: "General goal of AI?", o: ["تبريد الأجهزة", "محاكاة الذكاء البشري", "طباعة الورق", "شحن البطارية"], c: 1, d: 'EASY' },
  { ar: "ما المجال الفرعي من الذكاء الاصطناعي الذي يحاكي خلايا الدماغ بطبقات؟", en: "AI subfield modeled on brain cells?", o: ["قواعد البيانات", "الشبكات العصبية", "الجداول", "المتصفحات"], c: 1, d: 'HARD' },
  { ar: "ما اسم روبوت الدردشة الذي طورته OpenAI؟", en: "OpenAI's famous chatbot?", o: ["Claude", "ChatGPT", "Gemini", "Copilot"], c: 1 },
  { ar: "ما الشركة التي طوّرت نموذج «Claude»؟", en: "Company that built Claude?", o: ["جوجل", "Anthropic", "ميتا", "أمازون"], c: 1, d: 'HARD' },
  { ar: "ما المهمة التي يتعلم فيها النظام تمييز الصور (قطة أم كلب)؟", en: "Task of telling images apart (cat vs dog)?", o: ["الترجمة", "التصنيف", "الضغط", "التشفير"], c: 1, d: 'HARD' },
  { ar: "ماذا تعني «AI»؟", en: "What does AI mean?", o: ["الإنترنت المتقدم", "الذكاء الاصطناعي", "واجهة التطبيق", "تحليل المعلومات"], c: 1, d: 'EASY' },
  { ar: "ما النوع من التعلم الذي يعتمد على بيانات مُصنّفة مسبقاً؟", en: "Learning that uses pre-labeled data?", o: ["الخاضع للإشراف", "غير الخاضع للإشراف", "المعزز", "العشوائي"], c: 0, d: 'HARD' },
  { ar: "ما التقنية التي تتعرف على الوجوه في الصور؟", en: "Tech that recognizes faces in images?", o: ["الترجمة الآلية", "التعرف على الوجه", "التوليد", "التشفير"], c: 1 },
  { ar: "ما التقنية التي تحوّل النص المكتوب إلى صوت منطوق؟", en: "Tech converting text to speech?", o: ["تحويل النص إلى كلام", "التعرف على الوجه", "التصنيف", "الفلترة"], c: 0, d: 'HARD' },
  { ar: "ما البيانات الضخمة التي تُدرّب عليها النماذج عادةً؟", en: "Huge datasets used to train models?", o: ["الذاكرة المؤقتة", "البيانات الضخمة", "الواجهة", "الشبكة"], c: 1 },
  { ar: "ما الذي يعنيه أن يكون النموذج «مفتوح المصدر»؟", en: "What does \"open-source\" mean for a model?", o: ["كوده سري", "كوده متاح للجميع", "يعمل بلا إنترنت", "مجاني فقط"], c: 1 },
  { ar: "أي مما يلي مساعد صوتي ذكي؟", en: "Which of these is a voice assistant?", o: ["سيري", "فوتوشوب", "إكسل", "كروم"], c: 0, d: 'EASY' },
];
