/** الأنمي والكرتون — Anime & Cartoons. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const animeCartoon: BankQuestion[] = [
  { ar: "من البطل ذو القبعة الذي يريد أن يصبح ملك القراصنة؟", en: "Wants to be the Pirate King?", o: ["ناروتو", "لوفي", "غوكو", "إيتشيغو"], c: 1 },
  { ar: "في أي كرتون يطارد القط الفأر باستمرار؟", en: "Cat always chasing a mouse?", o: ["توم وجيري", "سبونج بوب", "بوكيمون", "باتمان"], c: 0, d: 'EASY' },
  { ar: "ما اسم البطل الذي يجمع المخلوقات في كرات؟", en: "Collects creatures in balls?", o: ["ديجيمون", "بوكيمون", "يوغي", "دراغون بول"], c: 1, d: 'EASY' },
  { ar: "ما اسم الإسفنجة الصفراء التي تعيش تحت الماء؟", en: "Yellow sponge under the sea?", o: ["سبونج بوب", "باتريك", "نيمو", "دوري"], c: 0, d: 'EASY' },
  { ar: "في أي أنمي يتدرب «غوكو» ليصبح أقوى محارب؟", en: "Goku trains to be the strongest?", o: ["ناروتو", "دراغون بول", "ون بيس", "بليتش"], c: 1 },
  { ar: "ما اسم النينجا صاحب الحلم بأن يصبح هوكاجي؟", en: "Ninja who dreams of becoming Hokage?", o: ["لوفي", "ناروتو", "غوكو", "إيتشيغو"], c: 1, d: 'EASY' },
  { ar: "ما اسم البوكيمون الأصفر الكهربائي الأشهر؟", en: "Most famous yellow electric Pokémon?", o: ["تشارمندر", "بيكاتشو", "بولباصور", "إيفي"], c: 1, d: 'EASY' },
  { ar: "ما الأنمي البوليسي عن طفل تحوّل من محقق بالغ؟", en: "Detective anime about a shrunken sleuth?", o: ["ناروتو", "المحقق كونان", "ون بيس", "بليتش"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي عن قاتل الشياطين «تانجيرو»؟", en: "Anime about demon-slayer Tanjiro?", o: ["ناروتو", "قاتل الشياطين", "بليتش", "ون بيس"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي عن الهجوم على العمالقة والأسوار؟", en: "Anime about titans attacking walls?", o: ["ناروتو", "هجوم العمالقة", "ون بيس", "بليتش"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون الأمريكي عن عائلة صفراء البشرة ساخرة؟", en: "US cartoon about a satirical yellow family?", o: ["عائلة سيمبسون", "سبونج بوب", "توم وجيري", "باتمان"], c: 0, d: 'HARD' },
  { ar: "ما الفأر الشهير شعار شركة ديزني؟", en: "Famous mouse, the Disney mascot?", o: ["جيري", "ميكي ماوس", "سبيدي", "بيكاتشو"], c: 1, d: 'EASY' },
  { ar: "ما الكرتون عن دب يحب العسل اسمه «ويني»؟", en: "Cartoon of a honey-loving bear named Winnie?", o: ["باندا", "ويني الدبدوب", "بو", "تيدي"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي عن فريق كرة قدم «الكابتن ماجد»؟", en: "Football anime \"Captain Majid\"?", o: ["ناروتو", "الكابتن ماجد", "أبطال الملاعب", "غريندايزر"], c: 1, d: 'HARD' },
  { ar: "ما الروبوت العملاق الفضائي الكلاسيكي الشهير؟", en: "Famous classic giant space robot?", o: ["مازنجر", "غريندايزر", "غاندام", "فولترون"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون الياباني عن نحلة صغيرة شجاعة؟", en: "Japanese cartoon about a brave little bee?", o: ["سالي", "زينا النحلة", "هايدي", "ساندي"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن فتاة تعيش في جبال الألب مع جدها؟", en: "Cartoon of a girl in the Alps with her grandfather?", o: ["سالي", "هايدي", "زينا", "ساندي"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي عن مفكرة تقتل من يُكتب اسمه فيها؟", en: "Anime about a deadly notebook?", o: ["ناروتو", "مذكرة الموت", "بليتش", "ون بيس"], c: 1, d: 'HARD' },
  { ar: "ما اسم صديق سبونج بوب نجم البحر الوردي؟", en: "SpongeBob's pink starfish friend?", o: ["سكويدوارد", "باتريك", "مستر كرابس", "بلانكتون"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي عن حصّاد الأرواح «إيتشيغو»؟", en: "Anime about soul-reaper Ichigo?", o: ["ناروتو", "بليتش", "ون بيس", "دراغون بول"], c: 1, d: 'HARD' },
  { ar: "ما لعبة البطاقات/الأنمي الشهير «يوغي يو»؟", en: "Famous card-dueling anime?", o: ["بوكيمون", "يوغي يو", "ديجيمون", "ناروتو"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي عن قط آلي أزرق من المستقبل؟", en: "Anime about a blue robotic cat from the future?", o: ["شين شان", "دورايمون", "كونان", "بوكيمون"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن سنجابين مرحين؟", en: "Cartoon about two playful chipmunks?", o: ["توم وجيري", "تشيب وديل", "ميكي", "باغز"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن فيل صغير طائر بأذنيه؟", en: "Cartoon of a little elephant that flies with its ears?", o: ["بامبي", "دمبو", "سيمبا", "بو"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون الكلاسيكي عن مغامر بحري اسمه «سندباد»؟", en: "Classic cartoon of the sailor Sinbad?", o: ["علاء الدين", "سندباد", "علي بابا", "عقلة الإصبع"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن أميرة بحذاء زجاجي «سندريلا»؟", en: "Cartoon of a princess with a glass slipper?", o: ["رابونزل", "سندريلا", "إلسا", "موانا"], c: 1, d: 'EASY' },
  { ar: "ما المسلسل الكرتوني الشهير عن كرة القدم «أبطال الملاعب»؟", en: "Famous football cartoon \"Captain Tsubasa\"?", o: ["ناروتو", "أبطال الملاعب", "هايكيو", "سلام دانك"], c: 1, d: 'HARD' },
  { ar: "ما الكائن الأصفر الذي يرافق «آش» في بوكيمون؟", en: "Ash's yellow companion in Pokémon?", o: ["تشارمندر", "بيكاتشو", "ميوتو", "إيفي"], c: 1, d: 'EASY' },
  { ar: "ما الكرتون الكوميدي عن طفل شقي «شين شان»؟", en: "Comedy cartoon about the mischievous Shin-chan?", o: ["كونان", "شين شان", "دورايمون", "ناروتو"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون الكلاسيكي للأرنب الرمادي الماكر؟", en: "Classic cartoon of a clever grey rabbit?", o: ["ميكي ماوس", "باغز باني", "توم", "جيري"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن أميرة نائمة توقظها قبلة؟", en: "Cartoon of a sleeping princess woken by a kiss?", o: ["سندريلا", "الجميلة النائمة", "رابونزل", "موانا"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي الشهير عن قراصنة وبطل مطّاطي «لوفي»؟", en: "Pirate anime with the rubber hero Luffy?", o: ["ناروتو", "ون بيس", "بليتش", "دراغون بول"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن مخلوقات رقمية «ديجيمون»؟", en: "Cartoon about digital monsters?", o: ["بوكيمون", "ديجيمون", "يوغي", "ناروتو"], c: 1, d: 'HARD' },
  { ar: "ما البطة الشهيرة في كرتون ديزني؟", en: "Famous Disney duck?", o: ["دافي", "دونالد دك", "سكروج", "بطوط"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن أرنب يأكل الجزر ويخدع الصياد؟", en: "Cartoon rabbit who eats carrots and fools the hunter?", o: ["ميكي", "باغز باني", "بيكاتشو", "سبيدي"], c: 1, d: 'HARD' },
  { ar: "ما البطل صاحب القبعة القشية الذي يريد أن يصبح ملك القراصنة؟", en: "Straw-hat hero who wants to be Pirate King?", o: ["ناروتو", "لوفي", "غوكو", "زورو"], c: 1 },
  { ar: "ما اسم البطل الذي يجمع المخلوقات في كرات صغيرة؟", en: "Hero who collects creatures in small balls?", o: ["ديجيمون", "بوكيمون", "يوغي", "دراغون بول"], c: 1, d: 'EASY' },
  { ar: "في أي كرتون يطارد القط الفأر باستمرار؟", en: "Cartoon where a cat always chases a mouse?", o: ["توم وجيري", "سبونج بوب", "بوكيمون", "باتمان"], c: 0, d: 'EASY' },
  { ar: "ما اسم الإسفنجة الصفراء التي تعيش تحت البحر؟", en: "Yellow sponge that lives under the sea?", o: ["سبونج بوب", "باتريك", "نيمو", "دوري"], c: 0, d: 'EASY' },
  { ar: "ما الأنمي الذي يتدرب فيه «غوكو» ويجمع كرات التنين؟", en: "Anime where Goku trains and gathers dragon balls?", o: ["ناروتو", "دراغون بول", "ون بيس", "بليتش"], c: 1 },
  { ar: "من البطل ذو القبعة الذي يريد أن يصبح ملك القراصنة؟", en: "The hatted hero who wants to be Pirate King?", o: ["ناروتو", "لوفي", "غوكو", "إيتشيغو"], c: 1 },
  { ar: "ما الكرتون الياباني الشهير بجمع المخلوقات في كرات (بوكيمون)؟", en: "Japanese cartoon about catching creatures in balls?", o: ["ديجيمون", "بوكيمون", "يوغي", "ناروتو"], c: 1, d: 'EASY' },
];
