/** الأنمي والكرتون — Anime & Cartoons. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const animeCartoon: BankQuestion[] = [
  { ar: "ما اسم البطل الذي يجمع المخلوقات في كرات؟", en: "Collects creatures in balls?", o: ["ديجيمون", "بوكيمون", "يوغي", "دراغون بول"], c: 1, d: 'EASY' },
  { ar: "ما اسم الإسفنجة الصفراء التي تعيش تحت الماء؟", en: "Yellow sponge under the sea?", o: ["سبونج بوب", "باتريك", "نيمو", "دوري"], c: 0, d: 'EASY' },
  { ar: "في أي أنمي يتدرب «غوكو» ليصبح أقوى محارب؟", en: "Goku trains to be the strongest?", o: ["ناروتو", "دراغون بول", "ون بيس", "بليتش"], c: 1 },
  { ar: "ما اسم النينجا صاحب الحلم بأن يصبح هوكاجي؟", en: "Ninja who dreams of becoming Hokage?", o: ["لوفي", "ناروتو", "غوكو", "إيتشيغو"], c: 1, d: 'EASY' },
  { ar: "ما اسم البوكيمون الأصفر الكهربائي الأشهر؟", en: "Most famous yellow electric Pokémon?", o: ["تشارمندر", "بيكاتشو", "بولباصور", "إيفي"], c: 1, d: 'EASY' },
  { ar: "ما الأنمي البوليسي عن طفل تحوّل من محقق بالغ؟", en: "Detective anime about a shrunken sleuth?", o: ["ناروتو", "المحقق كونان", "ون بيس", "بليتش"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي عن الهجوم على العمالقة والأسوار؟", en: "Anime about titans attacking walls?", o: ["ناروتو", "هجوم العمالقة", "ون بيس", "بليتش"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون الأمريكي عن عائلة صفراء البشرة ساخرة؟", en: "US cartoon about a satirical yellow family?", o: ["عائلة سيمبسون", "سبونج بوب", "توم وجيري", "باتمان"], c: 0, d: 'MEDIUM' },
  { ar: "ما الروبوت العملاق الفضائي الكلاسيكي الشهير؟", en: "Famous classic giant space robot?", o: ["مازنجر", "غريندايزر", "غاندام", "فولترون"], c: 1, d: 'MEDIUM' },
  { ar: "ما الأنمي عن مفكرة تقتل من يُكتب اسمه فيها؟", en: "Anime about a deadly notebook?", o: ["ناروتو", "مذكرة الموت", "بليتش", "ون بيس"], c: 1, d: 'HARD' },
  { ar: "ما اسم صديق سبونج بوب نجم البحر الوردي؟", en: "SpongeBob's pink starfish friend?", o: ["سكويدوارد", "باتريك", "مستر كرابس", "بلانكتون"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي عن حصّاد الأرواح «إيتشيغو»؟", en: "Anime about soul-reaper Ichigo?", o: ["ناروتو", "بليتش", "ون بيس", "دراغون بول"], c: 1, d: 'MEDIUM' },
  { ar: "ما الأنمي عن قط آلي أزرق من المستقبل؟", en: "Anime about a blue robotic cat from the future?", o: ["شين شان", "دورايمون", "كونان", "بوكيمون"], c: 1, d: 'MEDIUM' },
  { ar: "ما الكرتون عن فيل صغير طائر بأذنيه؟", en: "Cartoon of a little elephant that flies with its ears?", o: ["بامبي", "دمبو", "سيمبا", "بو"], c: 1, d: 'MEDIUM' },
  { ar: "ما الكائن الأصفر الذي يرافق «آش» في بوكيمون؟", en: "Ash's yellow companion in Pokémon?", o: ["تشارمندر", "بيكاتشو", "ميوتو", "إيفي"], c: 1, d: 'EASY' },
  { ar: "ما الكرتون الكلاسيكي للأرنب الرمادي الماكر؟", en: "Classic cartoon of a clever grey rabbit?", o: ["ميكي ماوس", "باغز باني", "توم", "جيري"], c: 1, d: 'MEDIUM' },
  { ar: "ما الكرتون عن أميرة نائمة توقظها قبلة؟", en: "Cartoon of a sleeping princess woken by a kiss?", o: ["سندريلا", "الجميلة النائمة", "رابونزل", "موانا"], c: 1, d: 'MEDIUM' },
  { ar: "ما الأنمي الشهير عن قراصنة وبطل مطّاطي «لوفي»؟", en: "Pirate anime with the rubber hero Luffy?", o: ["ناروتو", "ون بيس", "بليتش", "دراغون بول"], c: 1, d: 'HARD' },
  { ar: "ما البطة الشهيرة في كرتون ديزني؟", en: "Famous Disney duck?", o: ["دافي", "دونالد دك", "سكروج", "بطوط"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن أرنب يأكل الجزر ويخدع الصياد؟", en: "Cartoon rabbit who eats carrots and fools the hunter?", o: ["ميكي", "باغز باني", "بيكاتشو", "سبيدي"], c: 1, d: 'MEDIUM' },
  { ar: "ما البطل صاحب القبعة القشية الذي يريد أن يصبح ملك القراصنة؟", en: "Straw-hat hero who wants to be Pirate King?", o: ["ناروتو", "لوفي", "غوكو", "زورو"], c: 1 },
  { ar: "ما اسم البطل الذي يجمع المخلوقات في كرات صغيرة؟", en: "Hero who collects creatures in small balls?", o: ["ديجيمون", "بوكيمون", "يوغي", "دراغون بول"], c: 1, d: 'EASY' },
  { ar: "في أي كرتون يطارد القط الفأر باستمرار؟", en: "Cartoon where a cat always chases a mouse?", o: ["توم وجيري", "سبونج بوب", "بوكيمون", "باتمان"], c: 0, d: 'EASY' },
  { ar: "ما اسم الإسفنجة الصفراء التي تعيش تحت البحر؟", en: "Yellow sponge that lives under the sea?", o: ["سبونج بوب", "باتريك", "نيمو", "دوري"], c: 0, d: 'EASY' },
  { ar: "من البطل ذو القبعة الذي يريد أن يصبح ملك القراصنة؟", en: "The hatted hero who wants to be Pirate King?", o: ["ناروتو", "لوفي", "غوكو", "إيتشيغو"], c: 1 },
];
