/**
 * The question bank, assembled from one file per category.
 *
 * Keys are category slugs from prisma/taxonomy.ts. To add questions to a category,
 * append to that category's file — never to this index.
 *
 * Generated by prisma/splitBank.ts; the import list is maintained by hand from here on
 * (a new category = a new file + a line below).
 */
import type { BankQuestion } from './types.js';
import { whatSimilar } from './what-similar.js';
import { whatDifferent } from './what-different.js';
import { dialects } from './dialects.js';
import { dialectsArab } from './dialects-arab.js';
import { vision2030 } from './vision2030.js';
import { heritage } from './heritage.js';
import { heritageArab } from './heritage-arab.js';
import { nostalgia } from './nostalgia.js';
import { saudiLandmarks } from './saudi-landmarks.js';
import { worldLandmarks } from './world-landmarks.js';
import { worldCup } from './world-cup.js';
import { footballEurope } from './football-europe.js';
import { footballAsia } from './football-asia.js';
import { footballAfrica } from './football-africa.js';
import { footballSouthamerica } from './football-southamerica.js';
import { footballArab } from './football-arab.js';
import { footballGulf } from './football-gulf.js';
import { saudiLeague } from './saudi-league.js';
import { premierLeague } from './premier-league.js';
import { laliga } from './laliga.js';
import { general } from './general.js';
import { arabWorld } from './arab-world.js';
import { gulf } from './gulf.js';
import { history } from './history.js';
import { islamicHistory } from './islamic-history.js';
import { militaryHistory } from './military-history.js';
import { geography } from './geography.js';
import { flagsCapitals } from './flags-capitals.js';
import { currencies } from './currencies.js';
import { quran } from './quran.js';
import { islamicCulture } from './islamic-culture.js';
import { seerah } from './seerah.js';
import { prophetsCompanions } from './prophets-companions.js';
import { ramadanDrama } from './ramadan-drama.js';
import { moviesSeries } from './movies-series.js';
import { cinemaGulf } from './cinema-gulf.js';
import { cinemaLevant } from './cinema-levant.js';
import { animeCartoon } from './anime-cartoon.js';
import { artGulf } from './art-gulf.js';
import { artists } from './artists.js';
import { videoGames } from './video-games.js';
import { socialCelebs } from './social-celebs.js';
import { guess } from './guess.js';
import { worldWonders } from './world-wonders.js';
import { weirdFacts } from './weird-facts.js';
import { puzzlesLogic } from './puzzles-logic.js';
import { medicineHealth } from './medicine-health.js';
import { science } from './science.js';
import { space } from './space.js';
import { tech } from './tech.js';
import { ai } from './ai.js';
import { internetApps } from './internet-apps.js';
import { economy } from './economy.js';
import { scientistsInventors } from './scientists-inventors.js';
import { inventions } from './inventions.js';
import { arabicLiterature } from './arabic-literature.js';
import { poetry } from './poetry.js';
import { proverbs } from './proverbs.js';
import { cars } from './cars.js';
import { aviation } from './aviation.js';

export const QUESTION_BANK: Record<string, BankQuestion[]> = {
  'what-similar': whatSimilar,
  'what-different': whatDifferent,
  'dialects': dialects,
  'dialects-arab': dialectsArab,
  'vision2030': vision2030,
  'heritage': heritage,
  'heritage-arab': heritageArab,
  'nostalgia': nostalgia,
  'saudi-landmarks': saudiLandmarks,
  'world-landmarks': worldLandmarks,
  'world-cup': worldCup,
  'football-europe': footballEurope,
  'football-asia': footballAsia,
  'football-africa': footballAfrica,
  'football-southamerica': footballSouthamerica,
  'football-arab': footballArab,
  'football-gulf': footballGulf,
  'saudi-league': saudiLeague,
  'premier-league': premierLeague,
  'laliga': laliga,
  'general': general,
  'arab-world': arabWorld,
  'gulf': gulf,
  'history': history,
  'islamic-history': islamicHistory,
  'military-history': militaryHistory,
  'geography': geography,
  'flags-capitals': flagsCapitals,
  'currencies': currencies,
  'quran': quran,
  'islamic-culture': islamicCulture,
  'seerah': seerah,
  'prophets-companions': prophetsCompanions,
  'ramadan-drama': ramadanDrama,
  'movies-series': moviesSeries,
  'cinema-gulf': cinemaGulf,
  'cinema-levant': cinemaLevant,
  'anime-cartoon': animeCartoon,
  'art-gulf': artGulf,
  'artists': artists,
  'video-games': videoGames,
  'social-celebs': socialCelebs,
  'guess': guess,
  'world-wonders': worldWonders,
  'weird-facts': weirdFacts,
  'puzzles-logic': puzzlesLogic,
  'medicine-health': medicineHealth,
  'science': science,
  'space': space,
  'tech': tech,
  'ai': ai,
  'internet-apps': internetApps,
  'economy': economy,
  'scientists-inventors': scientistsInventors,
  'inventions': inventions,
  'arabic-literature': arabicLiterature,
  'poetry': poetry,
  'proverbs': proverbs,
  'cars': cars,
  'aviation': aviation,
};
