/** الثقافة الإسلامية — Islamic Culture. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const islamicCulture: BankQuestion[] = [
  { ar: "كم عدد أركان الإسلام؟", en: "How many pillars of Islam?", o: ["4", "5", "6", "7"], c: 1, d: 'EASY' },
  { ar: "كم عدد أركان الإيمان؟", en: "How many articles of faith?", o: ["5", "6", "7", "8"], c: 1, d: 'EASY' },
  { ar: "كم عدد الصلوات المفروضة في اليوم والليلة؟", en: "Daily obligatory prayers?", o: ["3", "4", "5", "6"], c: 2, d: 'EASY' },
  { ar: "كم ركعة في صلاة المغرب؟", en: "Rak'ahs in Maghrib prayer?", o: ["2", "3", "4", "5"], c: 1, d: 'EASY' },
  { ar: "كم ركعة في صلاة الفجر؟", en: "Rak'ahs in Fajr prayer?", o: ["2", "3", "4", "1"], c: 0, d: 'EASY' },
  { ar: "ما نسبة الزكاة في المال المدّخر إذا بلغ النصاب وحال عليه الحول؟", en: "Zakat rate on savings?", o: ["2.5%", "5%", "10%", "1%"], c: 0 },
  { ar: "ما اسم الطواف الذي يؤديه الحاج فور وصوله إلى مكة؟", en: "The arrival tawaf is called?", o: ["طواف القدوم", "طواف الوداع", "طواف الإفاضة", "السعي"], c: 0, d: 'HARD' },
  { ar: "ما اسم المكان الذي يقف فيه الحجاج في اليوم التاسع من ذي الحجة؟", en: "Where do pilgrims stand on 9 Dhul-Hijjah?", o: ["عرفة", "منى", "مزدلفة", "الصفا"], c: 0 },
  { ar: "كم عدد أشواط الطواف حول الكعبة؟", en: "Circuits of tawaf?", o: ["5", "7", "9", "3"], c: 1, d: 'EASY' },
  { ar: "بين أي جبلين يكون السعي في الحج والعمرة؟", en: "Sa'i is between which two hills?", o: ["الصفا والمروة", "أحد وثور", "عرفة ومنى", "حراء والنور"], c: 0, d: 'EASY' },
  { ar: "كم عدد الأشهر الحرم في التقويم الهجري؟", en: "How many sacred months?", o: ["2", "3", "4", "5"], c: 2 },
  { ar: "ما أول شهر في التقويم الهجري؟", en: "First month of the Hijri year?", o: ["محرم", "صفر", "رجب", "رمضان"], c: 0, d: 'EASY' },
  { ar: "ما الحدث الذي بدأ منه التقويم الهجري؟", en: "The Hijri calendar starts from?", o: ["الهجرة إلى المدينة", "فتح مكة", "غزوة بدر", "حجة الوداع"], c: 0 },
  { ar: "كم عدد أئمة المذاهب الفقهية السنية المشهورة؟", en: "How many major Sunni schools of law?", o: ["3", "4", "5", "6"], c: 1, d: 'EASY' },
  { ar: "من مؤلف الكتاب المعروف بأصح كتب الحديث بعد القرآن؟", en: "Author of the most authentic hadith collection?", o: ["الإمام البخاري", "الإمام مسلم", "أبو داود", "الترمذي"], c: 0 },
  { ar: "ما اسم الليلة التي وصفها القرآن بأنها خير من ألف شهر؟", en: "The night better than a thousand months?", o: ["ليلة القدر", "ليلة الإسراء", "ليلة النصف من شعبان", "ليلة الجمعة"], c: 0, d: 'EASY' },
  { ar: "ما العيد الذي يأتي مباشرة بعد شهر الصيام؟", en: "Which Eid follows the fasting month?", o: ["عيد الفطر", "عيد الأضحى", "رأس السنة الهجرية", "المولد"], c: 0, d: 'EASY' },
  { ar: "في أي يوم من ذي الحجة يكون عيد الأضحى؟", en: "Eid al-Adha falls on which day?", o: ["العاشر", "التاسع", "الأول", "الثالث عشر"], c: 0 },
  { ar: "ما اسم الصدقة الواجبة قبل صلاة العيد في نهاية رمضان؟", en: "Obligatory charity before Eid prayer?", o: ["زكاة الفطر", "زكاة المال", "الكفارة", "الفدية"], c: 0 },
  { ar: "ما اسم أول قبلة للمسلمين قبل تحويلها إلى الكعبة؟", en: "First qiblah before the Kaaba?", o: ["المسجد الأقصى", "مسجد قباء", "المسجد النبوي", "مسجد القبلتين"], c: 0 },
  { ar: "ما اسم أول مسجد بُني في الإسلام؟", en: "The first mosque built in Islam?", o: ["مسجد قباء", "المسجد النبوي", "المسجد الحرام", "مسجد القبلتين"], c: 0, d: 'HARD' },
  { ar: "كم عدد الكتب السماوية المذكورة في القرآن بالاسم؟", en: "Revealed books named in the Quran?", o: ["3", "4", "5", "6"], c: 1, d: 'HARD' },
  { ar: "ما اسم الملك الموكل بالوحي؟", en: "The angel of revelation?", o: ["جبريل", "ميكائيل", "إسرافيل", "مالك"], c: 0, d: 'EASY' },
  { ar: "ما اسم الوضوء البديل عند فقد الماء أو تعذّر استعماله؟", en: "Substitute for wudu without water?", o: ["التيمم", "الغسل", "المسح", "الاستنجاء"], c: 0 },
  { ar: "ما اسم صلاة الليل التي تُصلى جماعةً في رمضان؟", en: "Congregational night prayer in Ramadan?", o: ["التراويح", "الاستسقاء", "الكسوف", "الاستخارة"], c: 0, d: 'EASY' },
  { ar: "ما اسم الاعتكاف الذي يكون غالباً في العشر الأواخر من رمضان؟", en: "Seclusion in the last ten nights is called?", o: ["الاعتكاف", "القيام", "التهجد", "الخلوة"], c: 0, d: 'EASY' },
  { ar: "ما اسم العلم الذي يبحث في أحكام قراءة القرآن ومخارج الحروف؟", en: "The science of Quranic recitation rules?", o: ["التجويد", "التفسير", "أصول الفقه", "المصطلح"], c: 0 },
  { ar: "ما اسم العلم الذي يشرح معاني آيات القرآن؟", en: "The science explaining Quranic meanings?", o: ["التفسير", "التجويد", "النحو", "السيرة"], c: 0, d: 'EASY' },
  { ar: "كم عدد التكبيرات في الركعة الأولى من صلاة العيد عدا تكبيرة الإحرام؟", en: "Extra takbirs in the first rak'ah of Eid prayer?", o: ["سبع", "ست", "خمس", "ثلاث"], c: 1, d: 'HARD' },
  { ar: "ما اسم المكان الذي يبيت فيه الحجاج ليلة العيد بعد النزول من عرفة؟", en: "Where pilgrims spend the night after Arafah?", o: ["مزدلفة", "منى", "مكة", "الطائف"], c: 0, d: 'HARD' },
];
