/** الطب والصحة — Medicine & Health. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const medicineHealth: BankQuestion[] = [
  { ar: "كم عدد رئتي الإنسان؟", en: "How many lungs?", o: ["1", "2", "3", "4"], c: 1, d: 'EASY' },
  { ar: "ما العضو الذي يضخ الدم؟", en: "Organ that pumps blood?", o: ["الكبد", "القلب", "الكلى", "الرئة"], c: 1, d: 'EASY' },
  { ar: "ما الفيتامين الذي نحصل عليه من الشمس؟", en: "Vitamin from sunlight?", o: ["A", "C", "D", "B12"], c: 2 },
  { ar: "كم عدد أسنان الإنسان البالغ؟", en: "Adult human teeth?", o: ["28", "30", "32", "34"], c: 2 },
  { ar: "ما السائل الأحمر الذي يجري في الجسم؟", en: "Red fluid in the body?", o: ["الماء", "الدم", "اللعاب", "العرق"], c: 1, d: 'EASY' },
  { ar: "كم عدد عظام جسم الإنسان البالغ؟", en: "Bones in an adult human body?", o: ["106", "206", "306", "406"], c: 1 },
  { ar: "ما العضو المسؤول عن تنقية الدم وإفراز البول؟", en: "Organ filtering blood and making urine?", o: ["الكبد", "الكلى", "الرئة", "المعدة"], c: 1 },
  { ar: "ما العضو الأكبر في جسم الإنسان؟", en: "Largest organ in the human body?", o: ["الكبد", "الجلد", "القلب", "الرئة"], c: 1 },
  { ar: "ما الجهاز المسؤول عن هضم الطعام؟", en: "System responsible for digestion?", o: ["التنفسي", "الهضمي", "العصبي", "الدوري"], c: 1, d: 'EASY' },
  { ar: "ما الخلايا التي تدافع عن الجسم ضد الأمراض؟", en: "Cells that defend the body against disease?", o: ["الحمراء", "البيضاء", "الصفائح", "العصبية"], c: 1 },
  { ar: "ما المعدن المهم لصحة العظام والأسنان؟", en: "Mineral key for bones and teeth?", o: ["الحديد", "الكالسيوم", "الزنك", "الصوديوم"], c: 1 },
  { ar: "ما المعدن الذي يقل في حالة فقر الدم (الأنيميا)؟", en: "Mineral lacking in anemia?", o: ["الكالسيوم", "الحديد", "الزنك", "اليود"], c: 1, d: 'HARD' },
  { ar: "ما العضو الذي يُعد مركز التفكير والتحكم؟", en: "Organ that controls thinking?", o: ["القلب", "الدماغ", "الكبد", "المعدة"], c: 1, d: 'EASY' },
  { ar: "ما الوحدة الأساسية لبناء جسم الكائن الحي؟", en: "Basic building unit of a living body?", o: ["الذرة", "الخلية", "النسيج", "العضو"], c: 1 },
  { ar: "ما المرض الناتج عن ارتفاع سكر الدم؟", en: "Disease from high blood sugar?", o: ["الضغط", "السكري", "الربو", "الأنيميا"], c: 1, d: 'EASY' },
  { ar: "ما الأداة التي يستخدمها الطبيب لسماع نبض القلب والتنفس؟", en: "Doctor's tool for hearing heart and lungs?", o: ["المشرط", "السماعة الطبية", "الحقنة", "الأشعة"], c: 1, d: 'EASY' },
  { ar: "ما العضو الذي يخزّن الصفراء ويساعد على الهضم؟", en: "Organ storing bile to aid digestion?", o: ["الطحال", "المرارة", "البنكرياس", "الكلية"], c: 1, d: 'HARD' },
  { ar: "ما الهرمون الذي ينظّم سكر الدم ويفرزه البنكرياس؟", en: "Hormone from the pancreas regulating blood sugar?", o: ["الأدرينالين", "الإنسولين", "الكورتيزول", "الثيروكسين"], c: 1, d: 'HARD' },
  { ar: "ما المرض التنفسي المزمن الذي يسبّب ضيق الشعب الهوائية؟", en: "Chronic disease narrowing the airways?", o: ["السكري", "الربو", "الأنيميا", "الضغط"], c: 1 },
  { ar: "كم لتراً من الدم في جسم الإنسان البالغ تقريباً؟", en: "Approx. litres of blood in an adult?", o: ["2", "5", "10", "15"], c: 1, d: 'HARD' },
  { ar: "ما الجزء من العين الذي يحوّل الضوء إلى إشارات بصرية؟", en: "Eye part converting light to signals?", o: ["القرنية", "الشبكية", "القزحية", "العدسة"], c: 1, d: 'HARD' },
  { ar: "ما المرض المعدي الذي سبّب جائحة عالمية عام 2020؟", en: "Disease behind the 2020 pandemic?", o: ["الإنفلونزا", "كوفيد-19", "الملاريا", "السل"], c: 1 },
  { ar: "ما الذي يحمي الجسم من العدوى عبر تحفيز المناعة؟", en: "What protects via boosting immunity?", o: ["المسكّن", "اللقاح", "المضاد الحيوي", "الفيتامين"], c: 1 },
  { ar: "ما الدواء المستخدم ضد العدوى البكتيرية؟", en: "Medicine used against bacterial infection?", o: ["المسكّن", "المضاد الحيوي", "اللقاح", "الفيتامين"], c: 1 },
  { ar: "كم عدد ساعات النوم الموصى بها للبالغ يومياً تقريباً؟", en: "Recommended daily sleep for adults?", o: ["3-4 ساعات", "7-9 ساعات", "12-14 ساعة", "1-2 ساعة"], c: 1 },
  { ar: "ما العضو الذي يطرد ثاني أكسيد الكربون من الجسم؟", en: "Organ that expels carbon dioxide?", o: ["الكبد", "الرئتان", "الكلى", "المعدة"], c: 1 },
  { ar: "ما الذي يربط العضلات بالعظام؟", en: "What connects muscles to bones?", o: ["الأربطة", "الأوتار", "الغضاريف", "الأعصاب"], c: 1, d: 'HARD' },
  { ar: "ما الفحص الذي يصوّر العظام باستخدام الأشعة؟", en: "Imaging that shows bones via rays?", o: ["الموجات الصوتية", "الأشعة السينية", "تخطيط القلب", "تحليل الدم"], c: 1 },
  { ar: "ما العضو الذي يُصفّي السموم ويُنتج الصفراء؟", en: "Organ that filters toxins and makes bile?", o: ["الكلى", "الكبد", "الطحال", "البنكرياس"], c: 1, d: 'HARD' },
  { ar: "ما الجهاز الذي يشمل الدماغ والحبل الشوكي والأعصاب؟", en: "System of brain, spinal cord and nerves?", o: ["الدوري", "العصبي", "الهضمي", "التنفسي"], c: 1, d: 'HARD' },
  { ar: "ما الذي يحدث لمعدل ضربات القلب أثناء التمرين؟", en: "What happens to heart rate during exercise?", o: ["يقل", "يزداد", "يتوقف", "يثبت"], c: 1, d: 'EASY' },
  { ar: "ما الغذاء الذي يُعد مصدراً رئيسياً للبروتين؟", en: "Main source of protein?", o: ["السكر", "اللحوم والبقوليات", "الزيت", "الملح"], c: 1 },
  { ar: "ما الذي يسبّب تسوّس الأسنان غالباً؟", en: "Main cause of tooth decay?", o: ["الماء", "السكريات والبكتيريا", "الخضار", "النوم"], c: 1 },
  { ar: "ما المرض الذي يضعف جهاز المناعة (الإيدز)؟", en: "Disease that weakens the immune system?", o: ["السكري", "الإيدز", "الربو", "الضغط"], c: 1, d: 'HARD' },
  { ar: "ما النصيحة الأساسية للوقاية من الأمراض المعدية؟", en: "Key advice to prevent infections?", o: ["تجنب الماء", "غسل اليدين والنظافة", "قلة النوم", "كثرة السكر"], c: 1, d: 'EASY' },
  { ar: "ما المرض الناتج عن نقص فيتامين C عند البحارة قديماً؟", en: "Disease from vitamin C deficiency in old sailors?", o: ["الكساح", "الإسقربوط", "الأنيميا", "السكري"], c: 1, d: 'HARD' },
  { ar: "ما الجهاز الذي يقيس ضغط الدم؟", en: "Device that measures blood pressure?", o: ["الترمومتر", "جهاز قياس الضغط", "السماعة", "الأشعة"], c: 1 },
  { ar: "ما العملية التي يدخل بها الأكسجين ويخرج بها ثاني أكسيد الكربون؟", en: "Process of taking in O2 and expelling CO2?", o: ["الهضم", "التنفس", "الإخراج", "الدوران"], c: 1, d: 'EASY' },
  { ar: "ما أهمية شرب الماء للجسم؟", en: "Why is drinking water important?", o: ["لا فائدة", "الترطيب وأداء الوظائف الحيوية", "زيادة الوزن فقط", "لا شيء"], c: 1, d: 'EASY' },
  { ar: "ما الجهاز الذي يشمل القلب والأوعية الدموية؟", en: "System of the heart and blood vessels?", o: ["الهضمي", "الدوري", "العصبي", "التنفسي"], c: 1, d: 'HARD' },
  { ar: "كم عدد أسنان الإنسان البالغ؟", en: "Teeth in an adult human?", o: ["28", "30", "32", "34"], c: 2 },
  { ar: "ما الفيتامين الذي نحصل عليه من أشعة الشمس؟", en: "Vitamin we get from sunlight?", o: ["A", "C", "D", "B12"], c: 2 },
  { ar: "ما العضو الذي يضخ الدم في الجسم؟", en: "Organ that pumps blood?", o: ["الكبد", "القلب", "الكلى", "الرئة"], c: 1, d: 'EASY' },
  { ar: "كم عدد رئتي الإنسان؟", en: "How many lungs does a human have?", o: ["1", "2", "3", "4"], c: 1, d: 'EASY' },
  { ar: "ما العدد الطبيعي لحجرات قلب الإنسان؟", en: "Number of chambers in the human heart?", o: ["2", "3", "4", "5"], c: 2 },
];
