/** نوستالجيا التسعينات والثمانينات — 80s & 90s Nostalgia. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const nostalgia: BankQuestion[] = [
  { ar: "ما الجهاز المحمول الشهير للألعاب من نينتندو في التسعينات؟", en: "90s Nintendo handheld?", o: ["غيم بوي", "بلايستيشن", "إكس بوكس", "آيباد"], c: 0 },
  { ar: "ما القرص الذي كان يُستخدم لتخزين البيانات قديماً؟", en: "Old data storage disk?", o: ["USB", "الفلوبي", "SSD", "السحابة"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون الشهير عن قطة وفأر؟", en: "Classic cat-and-mouse cartoon?", o: ["توم وجيري", "بوكيمون", "سبايدرمان", "باتمان"], c: 0, d: 'EASY' },
  { ar: "ما الجهاز الذي كان يشغّل أشرطة الكاسيت؟", en: "Device that played cassette tapes?", o: ["المسجّل", "التلفاز", "الراديو الرقمي", "الجوال"], c: 0 },
  { ar: "ما لعبة المكعبات الورقية/الإلكترونية الشهيرة بترتيب الأشكال؟", en: "Classic falling-blocks game?", o: ["تيتريس", "ماريو", "سونيك", "باك مان"], c: 0 },
  { ar: "ما القرص الضوئي الذي حل محل الكاسيت لتخزين الموسيقى؟", en: "Optical disc that replaced cassettes for music?", o: ["الفلوبي", "السي دي (CD)", "USB", "الفينيل"], c: 1, d: 'HARD' },
  { ar: "ما الهاتف الذي اشتهر قبل الهواتف الذكية بصلابته؟", en: "Phone famous before smartphones for durability?", o: ["آيفون", "نوكيا", "جالاكسي", "هواوي"], c: 1, d: 'HARD' },
  { ar: "ما الجهاز الذي يعرض الأفلام عبر أشرطة الفيديو (VHS)؟", en: "Device that played VHS movie tapes?", o: ["DVD", "مشغّل VHS", "بلوراي", "نتفليكس"], c: 1, d: 'HARD' },
  { ar: "ما القرص الذي حل محل شريط الفيديو لمشاهدة الأفلام؟", en: "Disc that replaced video tapes for films?", o: ["الفلوبي", "الـDVD", "USB", "الكاسيت"], c: 1, d: 'HARD' },
  { ar: "ما الشخصية الكرتونية الإسفنجة الصفراء؟", en: "The yellow sponge cartoon character?", o: ["باتريك", "سبونج بوب", "نيمو", "دوري"], c: 1, d: 'EASY' },
  { ar: "ما اللعبة الإلكترونية للقنفذ الأزرق السريع؟", en: "Video game of the fast blue hedgehog?", o: ["ماريو", "سونيك", "تيتريس", "باك مان"], c: 1 },
  { ar: "ما الكرتون الياباني عن نحلة صغيرة شجاعة؟", en: "Japanese cartoon about a brave little bee?", o: ["سالي", "زينا النحلة", "هايدي", "ساندي"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن فتاة تعيش في جبال الألب مع جدها؟", en: "Cartoon of a girl in the Alps with her grandfather?", o: ["سالي", "هايدي", "زينا", "ساندي"], c: 1, d: 'HARD' },
  { ar: "ما اللعبة الشعبية بأكل النقاط والهروب من الأشباح؟", en: "Classic game of eating dots and dodging ghosts?", o: ["سونيك", "باك مان", "ماريو", "تيتريس"], c: 1, d: 'HARD' },
  { ar: "ما الوسيلة التي كان الناس يستخدمونها للاتصال خارج المنزل قبل الجوال؟", en: "How people called away from home before mobiles?", o: ["الإنترنت", "الهاتف العمومي", "الراديو", "الفاكس"], c: 1, d: 'HARD' },
  { ar: "ما الجهاز الذي يرسل ويستقبل المستندات عبر خط الهاتف؟", en: "Device sending documents over phone lines?", o: ["الإيميل", "الفاكس", "الراوتر", "الماسح"], c: 1, d: 'HARD' },
  { ar: "ما القناة الكرتونية العربية الشهيرة لأنميات التسعينات؟", en: "Famous Arabic 90s anime cartoon channel?", o: ["MBC3", "سبيستون", "براعم", "ماجد"], c: 1, d: 'HARD' },
  { ar: "ما المجلة العربية الشهيرة للأطفال؟", en: "Famous Arabic children's magazine?", o: ["العربي", "ماجد", "سمير", "ميكي"], c: 1, d: 'HARD' },
  { ar: "ما الأنمي عن فريق كرة قدم وبطل يُدعى «ماجد»؟", en: "Football anime with hero \"Majid\"?", o: ["أبطال الملاعب", "الكابتن ماجد", "هايكيو", "سلام دانك"], c: 1, d: 'HARD' },
  { ar: "ما الروبوت الفضائي العملاق الكلاسيكي الشهير؟", en: "Famous classic giant space robot?", o: ["مازنجر", "غريندايزر", "غاندام", "فولترون"], c: 1, d: 'HARD' },
  { ar: "ما القرص الكبير الأسود الذي يُشغّل الموسيقى قديماً جداً؟", en: "Large black disc for very old music players?", o: ["CD", "أسطوانة الفينيل", "الكاسيت", "USB"], c: 1, d: 'HARD' },
  { ar: "ما اللعبة الشعبية بالقفز على الحبل؟", en: "Folk game of jumping rope?", o: ["الشطرنج", "نط الحبل", "الورق", "الدومينو"], c: 1, d: 'EASY' },
  { ar: "ما الجهاز الذي كان يُستخدم لتشغيل الألعاب على التلفاز في التسعينات؟", en: "Device for playing 90s games on the TV?", o: ["الحاسوب فقط", "كونسول الألعاب", "الجوال", "التابلت"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن سنجابين مرحين؟", en: "Cartoon about two playful chipmunks?", o: ["توم وجيري", "تشيب وديل", "ميكي", "باغز"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون الكوميدي عن أرنب رمادي ماكر؟", en: "Comedy cartoon of a clever grey rabbit?", o: ["ميكي", "باغز باني", "سبيدي", "توم"], c: 1, d: 'HARD' },
  { ar: "ما اللعبة الشعبية التي تُلعب بكرات زجاجية ملونة صغيرة؟", en: "Folk game played with small glass marbles?", o: ["الكوتشينة", "البلي (الجلول)", "الدومينو", "الشطرنج"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن قط آلي أزرق من المستقبل؟", en: "Cartoon of a blue robotic cat from the future?", o: ["شين شان", "دورايمون", "كونان", "بوكيمون"], c: 1, d: 'HARD' },
  { ar: "ما الكرتون عن مغامر بحري اسمه «سندباد»؟", en: "Cartoon of the sea adventurer Sinbad?", o: ["علاء الدين", "سندباد", "علي بابا", "عقلة الإصبع"], c: 1, d: 'HARD' },
  { ar: "ما الجهاز المحمول من آبل لتشغيل الموسيقى الرقمية؟", en: "Apple's handheld digital music player?", o: ["آيفون", "آيبود", "آيباد", "ماك"], c: 1, d: 'HARD' },
  { ar: "ما الجهاز المنزلي للألعاب من سوني الذي ظهر في التسعينات؟", en: "Sony's 90s home game console?", o: ["إكس بوكس", "بلايستيشن", "سويتش", "غيم بوي"], c: 1 },
  { ar: "ما الفأر الشهير شعار شركة ديزني؟", en: "Famous mouse, the Disney mascot?", o: ["دونالد", "ميكي ماوس", "بلوتو", "جوفي"], c: 1, d: 'EASY' },
  { ar: "ما الكرتون عن دب يحب العسل اسمه «ويني»؟", en: "Cartoon of a honey-loving bear named Winnie?", o: ["باندا", "ويني الدبدوب", "بو", "تيدي"], c: 1, d: 'HARD' },
  { ar: "ما اللعبة الشعبية القديمة بالقفز على قدم واحدة بين مربعات؟", en: "Old folk game hopping on one foot between squares?", o: ["الغميضة", "الحجلة", "شد الحبل", "البلي"], c: 1, d: 'HARD' },
  { ar: "ما المشروب الغازي الأشهر عالمياً منذ عقود؟", en: "Most famous soft drink type for decades?", o: ["الماء", "الكولا", "العصير", "الشاي"], c: 1, d: 'EASY' },
  { ar: "ما الكرتون الياباني الشهير بجمع المخلوقات في كرات؟", en: "Japanese cartoon of catching creatures in balls?", o: ["ديجيمون", "بوكيمون", "يوغي", "ناروتو"], c: 1, d: 'EASY' },
  { ar: "ما الأداة الكروية التي كانت تُحرّك مؤشر الحاسوب قديماً؟", en: "Old ball-based device that moved the PC cursor?", o: ["الشاشة", "الفأرة", "الطابعة", "الراوتر"], c: 1, d: 'HARD' },
  { ar: "ما القرص المربع الذي كان يخزّن البيانات قديماً؟", en: "Square disk used to store data long ago?", o: ["USB", "الفلوبي", "SSD", "السحابة"], c: 1, d: 'HARD' },
  { ar: "ما الجهاز الذي كان يشغّل أشرطة الكاسيت؟", en: "Device that played cassette tapes?", o: ["المسجّل", "التلفاز", "الراديو الرقمي", "الجوال"], c: 0 },
  { ar: "ما الكرتون الشهير عن قطة وفأر يتطاردان؟", en: "Classic cat-and-mouse cartoon?", o: ["توم وجيري", "بوكيمون", "سبايدرمان", "باتمان"], c: 0, d: 'EASY' },
  { ar: "ما الجهاز المحمول الشهير للألعاب من نينتندو في التسعينات؟", en: "Nintendo's famous 90s handheld game device?", o: ["غيم بوي", "بلايستيشن", "إكس بوكس", "آيباد"], c: 0 },
  { ar: "ما لعبة الأشكال المتساقطة الشهيرة بترتيب المكعبات؟", en: "Famous game of arranging falling block shapes?", o: ["تيتريس", "ماريو", "سونيك", "باك مان"], c: 0 },
  { ar: "ما القرص المرن المربع الذي كان يُخزّن الملفات في التسعينات؟", en: "Square floppy disk used to store files in the 90s?", o: ["USB", "الفلوبي", "SSD", "السحابة"], c: 1, d: 'HARD' },
];
