/** الأنبياء والصحابة — Prophets & Companions. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const prophetsCompanions: BankQuestion[] = [
  { ar: "من النبي الذي كلّمه الله تكليماً؟", en: "Prophet whom Allah spoke to directly?", o: ["إبراهيم", "موسى", "عيسى", "نوح"], c: 1 },
  { ar: "من الصحابي الملقب بـ«سيف الله المسلول»؟", en: "\"The Drawn Sword of Allah\"?", o: ["خالد بن الوليد", "سعد بن أبي وقاص", "الزبير", "حمزة"], c: 0 },
  { ar: "من النبي الذي ابتلعه الحوت؟", en: "Prophet swallowed by the whale?", o: ["يونس", "أيوب", "يوسف", "صالح"], c: 0, d: 'EASY' },
  { ar: "من الصحابي الملقب بـ«الفاروق»؟", en: "Companion called \"Al-Farooq\"?", o: ["أبو بكر", "عمر بن الخطاب", "عثمان", "علي"], c: 1 },
  { ar: "أي نبي عُرف بصبره على البلاء؟", en: "Prophet known for patience in affliction?", o: ["أيوب", "يعقوب", "زكريا", "إدريس"], c: 0 },
  { ar: "من هو أبو الأنبياء؟", en: "Who is the \"father of the prophets\"?", o: ["نوح", "إبراهيم", "آدم", "موسى"], c: 1 },
  { ar: "من أول الأنبياء؟", en: "The first prophet?", o: ["نوح", "آدم", "إدريس", "شيث"], c: 1, d: 'EASY' },
  { ar: "من خاتم الأنبياء والمرسلين؟", en: "The final prophet?", o: ["عيسى", "محمد ﷺ", "موسى", "إبراهيم"], c: 1, d: 'EASY' },
  { ar: "أي نبي بنى السفينة ونجا من الطوفان؟", en: "Prophet of the ark and the flood?", o: ["هود", "نوح", "صالح", "لوط"], c: 1, d: 'EASY' },
  { ar: "أي نبي أُلقي في النار فكانت برداً وسلاماً؟", en: "Prophet thrown into a fire that turned cool?", o: ["موسى", "إبراهيم", "يوسف", "يونس"], c: 1 },
  { ar: "أي نبي فلق الله له البحر؟", en: "Prophet for whom the sea was parted?", o: ["عيسى", "موسى", "هارون", "يوشع"], c: 1 },
  { ar: "أي نبي كان يُحيي الموتى ويبرئ الأكمه والأبرص بإذن الله؟", en: "Prophet who revived the dead by God's leave?", o: ["موسى", "عيسى", "إدريس", "زكريا"], c: 1 },
  { ar: "أي نبي أُلين له الحديد؟", en: "Prophet for whom iron was made pliable?", o: ["سليمان", "داود", "أيوب", "يوسف"], c: 1, d: 'HARD' },
  { ar: "أي نبي سُخّرت له الرياح والجن والطير؟", en: "Prophet who controlled wind, jinn and birds?", o: ["داود", "سليمان", "أيوب", "إدريس"], c: 1 },
  { ar: "أي نبي ابتلعه الحوت؟", en: "Prophet swallowed by the whale?", o: ["أيوب", "يونس", "صالح", "هود"], c: 1 },
  { ar: "أي نبي فقد بصره حزناً على ابنه؟", en: "Prophet who lost his sight grieving for his son?", o: ["أيوب", "يعقوب", "زكريا", "نوح"], c: 1, d: 'HARD' },
  { ar: "أي نبي بُعث إلى قوم ثمود وكانت معجزته الناقة؟", en: "Prophet sent to Thamud with the she-camel?", o: ["هود", "صالح", "شعيب", "لوط"], c: 1, d: 'HARD' },
  { ar: "أي نبي بُعث إلى قوم عاد؟", en: "Prophet sent to the people of 'Aad?", o: ["صالح", "هود", "نوح", "لوط"], c: 1, d: 'HARD' },
  { ar: "أي نبي بُعث إلى أهل مدين؟", en: "Prophet sent to the people of Madyan?", o: ["لوط", "شعيب", "صالح", "هود"], c: 1, d: 'HARD' },
  { ar: "من زوجة فرعون التي آمنت بالله؟", en: "Pharaoh's wife who believed?", o: ["مريم", "آسية", "سارة", "هاجر"], c: 1, d: 'HARD' },
  { ar: "من ثاني الخلفاء الراشدين؟", en: "Second Rightly-Guided Caliph?", o: ["أبو بكر", "عمر", "عثمان", "علي"], c: 1 },
  { ar: "من ثالث الخلفاء الراشدين؟", en: "Third Rightly-Guided Caliph?", o: ["عمر", "عثمان", "علي", "معاوية"], c: 1 },
  { ar: "من رابع الخلفاء الراشدين؟", en: "Fourth Rightly-Guided Caliph?", o: ["عثمان", "علي بن أبي طالب", "معاوية", "الحسن"], c: 1 },
  { ar: "من الصحابي الملقب بذي النورين؟", en: "Companion called \"Possessor of Two Lights\"?", o: ["علي", "عثمان", "عمر", "الزبير"], c: 1 },
  { ar: "من الصحابي الملقب بأمين الأمة؟", en: "Companion called \"Trustee of the Ummah\"?", o: ["معاذ", "أبو عبيدة بن الجراح", "بلال", "أبو ذر"], c: 1, d: 'HARD' },
  { ar: "من الصحابي الذي لُقّب بحبر الأمة وترجمان القرآن؟", en: "Companion called \"Scholar of the Ummah\"?", o: ["ابن مسعود", "عبدالله بن عباس", "أبو هريرة", "أنس"], c: 1, d: 'HARD' },
  { ar: "من أكثر الصحابة روايةً للحديث؟", en: "Companion who narrated the most hadith?", o: ["ابن عمر", "أبو هريرة", "أنس", "عائشة"], c: 1 },
  { ar: "من الصحابي الذي جمع القرآن في مصحف بأمر أبي بكر؟", en: "Companion who compiled the Quran under Abu Bakr?", o: ["أبي بن كعب", "زيد بن ثابت", "ابن مسعود", "معاذ"], c: 1, d: 'HARD' },
  { ar: "من خادم النبي ﷺ الذي لازمه عشر سنين؟", en: "The Prophet's servant for ten years?", o: ["أبو هريرة", "أنس بن مالك", "ابن عباس", "بلال"], c: 1, d: 'HARD' },
  { ar: "من الصحابية الملقبة بذات النطاقين؟", en: "Companion called \"She of the Two Belts\"?", o: ["عائشة", "أسماء بنت أبي بكر", "خديجة", "أم سلمة"], c: 1, d: 'HARD' },
  { ar: "من الصحابي الذي فتح الأندلس؟", en: "Commander who conquered Andalusia?", o: ["عقبة بن نافع", "طارق بن زياد", "خالد بن الوليد", "المثنى"], c: 1 },
  { ar: "من القائد الذي فتح مصر؟", en: "Commander who conquered Egypt?", o: ["خالد", "عمرو بن العاص", "سعد", "أبو عبيدة"], c: 1, d: 'HARD' },
  { ar: "أي نبي رفعه الله إليه ولم يُقتل؟", en: "Prophet raised up to God, not killed?", o: ["موسى", "عيسى", "إدريس", "يحيى"], c: 1, d: 'HARD' },
  { ar: "أي نبي آتاه الله الحكم صبياً؟", en: "Prophet given wisdom as a boy?", o: ["عيسى", "يحيى", "سليمان", "يوسف"], c: 1, d: 'HARD' },
  { ar: "أي نبي هو ابن إبراهيم وأبو يعقوب؟", en: "Prophet, son of Ibrahim and father of Ya'qub?", o: ["إسماعيل", "إسحاق", "يوسف", "هود"], c: 1, d: 'HARD' },
  { ar: "من بنى الكعبة مع ابنه إسماعيل؟", en: "Who built the Kaaba with his son Ismail?", o: ["نوح", "إبراهيم", "آدم", "محمد"], c: 1 },
  { ar: "أي نبي رأى رؤيا أحد عشر كوكباً والشمس والقمر؟", en: "Prophet who dreamt of 11 stars, the sun and moon?", o: ["يعقوب", "يوسف", "إبراهيم", "موسى"], c: 1 },
  { ar: "من أخو موسى الذي كان نبياً وعوناً له؟", en: "Moses' brother who was also a prophet?", o: ["شعيب", "هارون", "يوشع", "الخضر"], c: 1, d: 'HARD' },
  { ar: "من الصحابي الذي دعا له النبي ﷺ فأعزّ الله به الإسلام؟", en: "Companion whose Islam strengthened the faith (Al-Farooq)?", o: ["أبو جهل", "عمر بن الخطاب", "أبو لهب", "الوليد"], c: 1, d: 'HARD' },
  { ar: "من أول من جهر بقراءة القرآن في مكة؟", en: "First to recite the Quran aloud in Mecca?", o: ["بلال", "عبدالله بن مسعود", "عمار", "أبو بكر"], c: 1, d: 'HARD' },
  { ar: "من الصحابي الذي اهتز لموته عرش الرحمن؟", en: "Companion at whose death \"the Throne shook\"?", o: ["سعد بن أبي وقاص", "سعد بن معاذ", "سعد بن عبادة", "أبو دجانة"], c: 1, d: 'HARD' },
  { ar: "كم عدد أولي العزم من الرسل؟", en: "How many \"Ulul-Azm\" messengers?", o: ["3", "5", "7", "10"], c: 1, d: 'HARD' },
  { ar: "من النبي الذي وهبه الله ملكاً عظيماً لا ينبغي لأحد من بعده؟", en: "Prophet given a kingdom none after him would have?", o: ["داود", "سليمان", "يوسف", "ذو القرنين"], c: 1, d: 'HARD' },
  { ar: "من أول من آمن من الرجال الأحرار؟", en: "First free man to embrace Islam?", o: ["عمر", "أبو بكر", "عثمان", "علي"], c: 1, d: 'HARD' },
  { ar: "أي نبي يُلقب بـ«كليم الله» لأن الله كلّمه تكليماً؟", en: "Prophet titled \"the one God spoke to\"?", o: ["إبراهيم", "موسى", "عيسى", "نوح"], c: 1 },
];
