/** القرآن الكريم — The Holy Quran. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const quran: BankQuestion[] = [
  { ar: "كم عدد سور القرآن الكريم؟", en: "Number of surahs in the Quran?", o: ["110", "112", "114", "116"], c: 2, d: 'EASY' },
  { ar: "ما أطول سورة في القرآن؟", en: "Longest surah?", o: ["آل عمران", "البقرة", "النساء", "الأعراف"], c: 1 },
  { ar: "ما السورة التي تعدل ثلث القرآن؟", en: "Surah equal to a third of the Quran?", o: ["الفاتحة", "الإخلاص", "الكوثر", "الناس"], c: 1 },
  { ar: "بأي سورة يبدأ القرآن الكريم؟", en: "Quran opens with which surah?", o: ["البقرة", "الفاتحة", "يس", "الكهف"], c: 1, d: 'EASY' },
  { ar: "ما أقصر سورة في القرآن؟", en: "Shortest surah?", o: ["الكوثر", "الإخلاص", "العصر", "الفلق"], c: 0, d: 'HARD' },
  { ar: "كم عدد أجزاء القرآن الكريم؟", en: "Number of juz' in the Quran?", o: ["20", "30", "40", "60"], c: 1, d: 'EASY' },
  { ar: "كم عدد آيات سورة الفاتحة؟", en: "Verses in Surah Al-Fatihah?", o: ["5", "6", "7", "8"], c: 2 },
  { ar: "ما أول سورة نزلت من القرآن الكريم؟", en: "First surah revealed?", o: ["الفاتحة", "العلق", "المدثر", "الناس"], c: 1, d: 'HARD' },
  { ar: "ما آخر سورة في ترتيب المصحف؟", en: "Last surah in the mushaf order?", o: ["الفلق", "الناس", "الإخلاص", "المسد"], c: 1 },
  { ar: "ما السورة التي تُسمى «قلب القرآن»؟", en: "Surah called \"the heart of the Quran\"?", o: ["الرحمن", "يس", "الملك", "الكهف"], c: 1, d: 'HARD' },
  { ar: "ما السورة الوحيدة التي لا تبدأ بالبسملة؟", en: "Only surah not starting with the Basmalah?", o: ["الفاتحة", "التوبة", "النمل", "الإخلاص"], c: 1, d: 'HARD' },
  { ar: "في أي سورة وردت البسملة مرتين؟", en: "Surah with the Basmalah twice?", o: ["التوبة", "النمل", "الفاتحة", "يس"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي يُستحب قراءتها يوم الجمعة؟", en: "Surah recommended on Fridays?", o: ["يس", "الكهف", "الملك", "الواقعة"], c: 1 },
  { ar: "ما السورة التي تبدأ بـ«قل هو الله أحد»؟", en: "Surah starting \"Say: He is Allah, One\"?", o: ["الكافرون", "الإخلاص", "الفلق", "الناس"], c: 1, d: 'EASY' },
  { ar: "ما المعوذتان في القرآن الكريم؟", en: "The two \"Mu'awwidhatan\"?", o: ["الإخلاص والكوثر", "الفلق والناس", "الفاتحة والبقرة", "يس والملك"], c: 1 },
  { ar: "ما السورة التي ورد فيها ذكر «ذي القرنين»؟", en: "Surah mentioning Dhul-Qarnayn?", o: ["الكهف", "مريم", "طه", "النمل"], c: 0, d: 'HARD' },
  { ar: "ما السورة التي سُميت باسم معدن؟", en: "Surah named after a metal?", o: ["النحل", "الحديد", "النور", "الفجر"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي سُميت باسم حشرة تبني بيتاً واهياً؟", en: "Surah named after an insect with a frail home?", o: ["النحل", "العنكبوت", "النمل", "الفيل"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي ذُكرت فيها قصة أصحاب الفيل؟", en: "Surah on the Companions of the Elephant?", o: ["قريش", "الفيل", "الماعون", "الهمزة"], c: 1 },
  { ar: "ما السورة التي تُسمى «أم الكتاب»؟", en: "Surah called \"the Mother of the Book\"?", o: ["البقرة", "الفاتحة", "يس", "الإخلاص"], c: 1 },
  { ar: "كم عدد آيات سورة الإخلاص؟", en: "Verses in Surah Al-Ikhlas?", o: ["3", "4", "5", "6"], c: 1 },
  { ar: "ما اللغة التي نزل بها القرآن الكريم؟", en: "Language of the Quran's revelation?", o: ["السريانية", "العربية", "العبرية", "الفارسية"], c: 1, d: 'EASY' },
  { ar: "في أي شهر بدأ نزول القرآن الكريم؟", en: "Month the Quran began to be revealed?", o: ["شعبان", "رمضان", "رجب", "محرم"], c: 1 },
  { ar: "ما الليلة المباركة التي أُنزل فيها القرآن؟", en: "Blessed night of the Quran's revelation?", o: ["ليلة الإسراء", "ليلة القدر", "ليلة النصف من شعبان", "ليلة الجمعة"], c: 1 },
  { ar: "كم سنة استغرق نزول القرآن الكريم تقريباً؟", en: "Years over which the Quran was revealed?", o: ["10", "13", "23", "40"], c: 2, d: 'HARD' },
  { ar: "في أي سورة وردت آية الكرسي؟", en: "Surah containing Ayat al-Kursi?", o: ["آل عمران", "البقرة", "النساء", "المائدة"], c: 1 },
  { ar: "ما أعظم آية في القرآن الكريم؟", en: "Greatest verse in the Quran?", o: ["أول البقرة", "آية الكرسي", "آية الدَّين", "الفاتحة"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي ذُكر فيها لقمان ووصاياه لابنه؟", en: "Surah with Luqman's advice to his son?", o: ["الكهف", "لقمان", "مريم", "طه"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي سُميت باسم امرأة؟", en: "Surah named after a woman?", o: ["النساء", "مريم", "الطلاق", "المجادلة"], c: 1 },
  { ar: "ما السورة التي ذُكرت فيها قصة أصحاب الكهف؟", en: "Surah of the People of the Cave?", o: ["مريم", "الكهف", "طه", "يس"], c: 1 },
  { ar: "ما السورة التي تتكرر فيها «فبأي آلاء ربكما تكذبان»؟", en: "Surah repeating \"Which favours...will you deny?\"?", o: ["الواقعة", "الرحمن", "القمر", "النجم"], c: 1 },
  { ar: "ما السورة الملقبة بـ«عروس القرآن»؟", en: "Surah called \"the bride of the Quran\"?", o: ["الواقعة", "الرحمن", "يس", "الملك"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي تُسمى «الفاضحة» لكشفها المنافقين؟", en: "Surah that exposed the hypocrites?", o: ["الأنفال", "التوبة", "النور", "الأحزاب"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي ورد فيها طوفان نوح باسمها؟", en: "Surah named after the prophet of the flood?", o: ["نوح", "هود", "يونس", "الأنبياء"], c: 0, d: 'HARD' },
  { ar: "كم مرة ذُكر اسم النبي «محمد» صراحةً في القرآن؟", en: "Times the name \"Muhammad\" appears in the Quran?", o: ["1", "4", "10", "25"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي تُسمى باسم يوم القيامة؟", en: "Surah named after the Day of Resurrection?", o: ["الواقعة", "القيامة", "الحاقة", "القارعة"], c: 1, d: 'HARD' },
  { ar: "ما أطول آية في القرآن الكريم؟", en: "Longest verse in the Quran?", o: ["آية الكرسي", "آية الدَّين", "أول الكوثر", "الفاتحة"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي تعادل قراءتها ربع القرآن؟", en: "Surah equal to a quarter of the Quran?", o: ["الإخلاص", "الكافرون", "الزلزلة", "النصر"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي تبدأ بـ«الحمد لله رب العالمين»؟", en: "Surah starting \"Praise be to Allah, Lord of the worlds\"?", o: ["البقرة", "الفاتحة", "الأنعام", "الكهف"], c: 1, d: 'EASY' },
  { ar: "ما السورة التي بها سجدة تلاوة وتبدأ بـ«الم تنزيل»؟", en: "Surah with a prostration starting \"Alif-Lam-Mim Tanzeel\"?", o: ["فصلت", "السجدة", "ص", "النجم"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي تتحدث عن الاستعاذة من شر الوسواس؟", en: "Surah seeking refuge from the whisperer?", o: ["الفلق", "الناس", "الكافرون", "المسد"], c: 1, d: 'HARD' },
  { ar: "كم عدد السور التي سُميت بأسماء أنبياء؟", en: "How many surahs are named after prophets?", o: ["4", "6", "8", "10"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي تُسمى «المنجية» وتشفع لصاحبها؟", en: "Protective surah said to intercede for its reciter?", o: ["الكهف", "الملك", "يس", "الواقعة"], c: 1, d: 'HARD' },
  { ar: "ما السورة التي تحكي قصة يوسف وتُسمى «أحسن القصص»؟", en: "Surah of Yusuf called \"the best of stories\"?", o: ["هود", "يوسف", "إبراهيم", "نوح"], c: 1 },
  { ar: "ما أطول سورة في القرآن الكريم؟", en: "Longest surah in the Quran?", o: ["آل عمران", "البقرة", "النساء", "الأعراف"], c: 1 },
];
