/** معالم ومدن المملكة — Saudi Landmarks & Cities. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const saudiLandmarks: BankQuestion[] = [
  { ar: "في أي مدينة يقع المسجد الحرام؟", en: "City of the Grand Mosque?", o: ["المدينة", "مكة", "الطائف", "جدة"], c: 1, d: 'EASY' },
  { ar: "ما المحافظة السعودية الشهيرة بالمدائن الأثرية والصخور؟", en: "Saudi site famous for rock tombs?", o: ["العلا", "أبها", "حائل", "الأحساء"], c: 0 },
  { ar: "ما المدينة السعودية المطلة على البحر الأحمر وتُلقب «عروس البحر الأحمر»؟", en: "\"Bride of the Red Sea\"?", o: ["ينبع", "جدة", "الدمام", "جازان"], c: 1 },
  { ar: "ما الواحة السعودية المدرجة في التراث العالمي وتشتهر بالنخيل؟", en: "Palm-oasis World Heritage site?", o: ["الأحساء", "القصيم", "الجوف", "نجران"], c: 0, d: 'HARD' },
  { ar: "في أي مدينة سعودية يقع برج المملكة ذو الفتحة العلوية؟", en: "Saudi city of the Kingdom Centre tower?", o: ["جدة", "الرياض", "الدمام", "مكة"], c: 1 },
  { ar: "ما العاصمة الإدارية لمنطقة عسير ذات المرتفعات؟", en: "Capital of the highland Asir region?", o: ["نجران", "أبها", "جازان", "الباحة"], c: 1, d: 'MEDIUM' },
  { ar: "ما العاصمة الإدارية لمنطقة القصيم؟", en: "Capital of the Qassim region?", o: ["عنيزة", "بريدة", "الرس", "المذنب"], c: 1, d: 'MEDIUM' },
  { ar: "ما المدينة السعودية الصناعية على ساحل الخليج العربي؟", en: "Saudi industrial city on the Gulf?", o: ["ينبع", "الجبيل", "رابغ", "الخفجي"], c: 1, d: 'MEDIUM' },
  { ar: "ما المدينة السعودية الصناعية على ساحل البحر الأحمر؟", en: "Saudi industrial city on the Red Sea?", o: ["الجبيل", "ينبع", "رأس الخير", "الخفجي"], c: 1, d: 'MEDIUM' },
  { ar: "ما المنطقة السعودية المشهورة بجبلي أجا وسلمى؟", en: "Saudi region of the Aja and Salma mountains?", o: ["تبوك", "حائل", "القصيم", "الجوف"], c: 1, d: 'MEDIUM' },
  { ar: "ما العاصمة التاريخية للدولة السعودية الأولى؟", en: "Capital of the First Saudi State?", o: ["الرياض", "الدرعية", "الدمام", "حائل"], c: 1, d: 'MEDIUM' },
  { ar: "ما المشروع السعودي للمدينة المستقبلية شمال غرب المملكة؟", en: "Saudi futuristic NW megacity?", o: ["نيوم", "القدية", "روشن", "أمالا"], c: 0 },
  { ar: "ما أعلى قمة جبلية في السعودية تقع في منطقة عسير؟", en: "Highest peak in Saudi Arabia (Asir)?", o: ["جبل السودة", "جبل طويق", "جبل أحد", "جبل النور"], c: 0, d: 'MEDIUM' },
  { ar: "ما الجبل المطل على المدينة المنورة المرتبط بغزوة شهيرة؟", en: "Mountain by Medina linked to a famous battle?", o: ["جبل النور", "جبل أحد", "جبل ثور", "جبل طويق"], c: 1, d: 'HARD' },
  { ar: "ما الغار الذي نزل فيه الوحي ويقع في جبل النور بمكة؟", en: "Cave of the first revelation near Mecca?", o: ["غار ثور", "غار حراء", "غار الكهف", "غار الأرقم"], c: 1, d: 'HARD' },
  { ar: "ما المدينة السعودية المعروفة بالمصيف واعتدال الجو؟", en: "Saudi cool-summer highland city?", o: ["تبوك", "أبها", "حفر الباطن", "سكاكا"], c: 1 },
  { ar: "ما الجسر الذي يربط السعودية بمملكة البحرين؟", en: "Bridge linking KSA and Bahrain?", o: ["جسر الملك فهد", "جسر جابر", "جسر السلام", "جسر الملك سلمان"], c: 0 },
  { ar: "ما الخليج الواقع شمال غرب السعودية قرب تبوك؟", en: "Gulf NW of Saudi Arabia near Tabuk?", o: ["خليج العقبة", "خليج عمان", "خليج البحرين", "الخليج العربي"], c: 0, d: 'MEDIUM' },
  { ar: "ما المدينة السعودية التي يقع فيها المقر الرئيسي لأرامكو؟", en: "Saudi city of Aramco HQ?", o: ["الدمام", "الظهران", "الخبر", "الجبيل"], c: 1, d: 'HARD' },
  { ar: "ما أكبر مدينة في المنطقة الشرقية؟", en: "Largest city in the Eastern Province?", o: ["الخبر", "الدمام", "الأحساء", "الجبيل"], c: 1 },
  { ar: "ما المدينة السعودية التي تشتهر بالورد الطائفي؟", en: "Saudi city famed for Taif roses?", o: ["أبها", "الطائف", "الباحة", "نجران"], c: 1 },
  { ar: "ما المتنزه الوطني الجبلي قرب أبها؟", en: "Mountain national park near Abha?", o: ["السودة", "الثمامة", "رغدان", "الحبلة"], c: 0, d: 'MEDIUM' },
  { ar: "ما المنطقة السعودية الجنوبية الحدودية المعروفة ببيوتها التراثية الملونة؟", en: "Southern Saudi region of colourful heritage houses?", o: ["نجران", "عسير", "جازان", "الباحة"], c: 1, d: 'HARD' },
  { ar: "ما البرج الشهير في الرياض على شكل مفتاح زجاجي؟", en: "Riyadh tower shaped like a bottle-opener?", o: ["الفيصلية", "المملكة", "رافال", "الأنماء"], c: 0, d: 'MEDIUM' },
  { ar: "ما المدينة السعودية الساحلية على الخليج المعروفة بالكورنيش؟", en: "Saudi Gulf city known for its corniche?", o: ["جدة", "الخبر", "ينبع", "جازان"], c: 1, d: 'MEDIUM' },
  { ar: "ما عاصمة المملكة العربية السعودية؟", en: "Capital of Saudi Arabia?", o: ["جدة", "الرياض", "مكة", "الدمام"], c: 1, d: 'EASY' },
  { ar: "ما المنطقة التي يقع فيها وادي الدواسر جنوب نجد؟", en: "Region of Wadi al-Dawasir in southern Najd?", o: ["الرياض", "عسير", "جازان", "الحدود الشمالية"], c: 0, d: 'HARD' },
  { ar: "ما المدينة السعودية الحدودية الشمالية المعروفة بآثار قلعة مارد؟", en: "Northern Saudi city with Marid Castle?", o: ["سكاكا (الجوف)", "عرعر", "تبوك", "حائل"], c: 0, d: 'HARD' },
  { ar: "ما المدينة المقدسة التي تُقام فيها مناسك الحج سنوياً؟", en: "Holy city of the annual Hajj?", o: ["المدينة", "مكة", "الطائف", "جدة"], c: 1, d: 'EASY' },
  { ar: "ما الجبل الذي تبدأ منه مناسك يوم عرفة قرب مكة؟", en: "Mount of the Day of Arafah near Mecca?", o: ["جبل النور", "جبل عرفات", "جبل أحد", "جبل ثور"], c: 1, d: 'MEDIUM' },
  { ar: "ما المنطقة السعودية المشهورة بزراعة القمح والحبوب؟", en: "Saudi region known for wheat farming?", o: ["القصيم", "جازان", "نجران", "تبوك"], c: 0, d: 'HARD' },
  { ar: "ما المنطقة السعودية الجنوبية الزراعية المطيرة على البحر الأحمر؟", en: "Rainy southern Saudi farming region on the Red Sea?", o: ["تبوك", "جازان", "الجوف", "حائل"], c: 1, d: 'HARD' },
  { ar: "ما المشروع الترفيهي العملاق المقام قرب الرياض؟", en: "Giant entertainment project near Riyadh?", o: ["نيوم", "القدية", "روشن", "البحر الأحمر"], c: 1 },
  { ar: "ما المدينة التاريخية عاصمة الدولة السعودية الأولى المطوّرة سياحياً؟", en: "Historic capital of the first state, now a tourism hub?", o: ["جدة", "الدرعية", "أبها", "تبوك"], c: 1, d: 'MEDIUM' },
  { ar: "ما الصحراء الكبرى جنوب السعودية المشتركة مع اليمن وعُمان؟", en: "Great desert south of KSA shared with Yemen & Oman?", o: ["النفود الكبير", "الربع الخالي", "الدهناء", "صحراء نجد"], c: 1, d: 'MEDIUM' },
  { ar: "ما المنطقة الإدارية التي تقع فيها مدينة جدة؟", en: "Administrative region of the city of Jeddah?", o: ["الرياض", "مكة المكرمة", "المدينة", "عسير"], c: 1, d: 'MEDIUM' },
  { ar: "ما المدينة الجبلية في الجنوب المعروفة بمدرجاتها الزراعية؟", en: "Southern mountain city of terraced farms?", o: ["أبها", "الباحة", "تنومة", "النماص"], c: 1, d: 'MEDIUM' },
  { ar: "في أي مدينة سعودية يقع المسجد الحرام والكعبة المشرفة؟", en: "City of the Grand Mosque and Kaaba?", o: ["المدينة", "مكة", "الطائف", "جدة"], c: 1, d: 'EASY' },
  { ar: "ما المحافظة السعودية المسجّلة في التراث العالمي وتشتهر بمدائن صالح؟", en: "Saudi UNESCO governorate famed for Madain Salih?", o: ["العلا", "أبها", "حائل", "الأحساء"], c: 0 },
];
