/** علماء ومخترعون — Scientists & Inventors. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const scientistsInventors: BankQuestion[] = [
  { ar: "من يُلقب بـ«أبو الطب» من علماء المسلمين؟", en: "Muslim \"Father of Medicine\"?", o: ["ابن سينا", "الخوارزمي", "ابن الهيثم", "جابر بن حيان"], c: 0 },
  { ar: "من العالم المسلم المؤسس لعلم الجبر؟", en: "Founder of algebra?", o: ["الخوارزمي", "البيروني", "ابن رشد", "الرازي"], c: 0, d: 'HARD' },
  { ar: "من رائد علم البصريات من المسلمين؟", en: "Pioneer of optics?", o: ["ابن الهيثم", "ابن سينا", "الكندي", "الفارابي"], c: 0 },
  { ar: "من يُعد رائد علم الكيمياء عند المسلمين؟", en: "Pioneer of chemistry?", o: ["جابر بن حيان", "الخوارزمي", "ابن خلدون", "الإدريسي"], c: 0, d: 'HARD' },
  { ar: "من العالم المسلم المؤسس لعلم الاجتماع؟", en: "Founder of sociology?", o: ["ابن خلدون", "ابن بطوطة", "الإدريسي", "الرازي"], c: 0 },
  { ar: "ما كتاب ابن سينا الشهير الذي ظل مرجعاً للطب قروناً؟", en: "Ibn Sina's famous medical reference?", o: ["الحاوي", "القانون في الطب", "المناظر", "الجبر"], c: 1, d: 'HARD' },
  { ar: "من العالم المسلم صاحب موسوعة «الحاوي» في الطب؟", en: "Author of the medical encyclopedia \"Al-Hawi\"?", o: ["ابن سينا", "الرازي", "ابن النفيس", "الزهراوي"], c: 1, d: 'HARD' },
  { ar: "من العالم المسلم الذي وصف الدورة الدموية الصغرى؟", en: "Muslim scholar who described pulmonary circulation?", o: ["ابن سينا", "ابن النفيس", "الرازي", "الزهراوي"], c: 1, d: 'HARD' },
  { ar: "من يُلقب بـ«أبو الجراحة» من علماء المسلمين؟", en: "Muslim \"Father of Surgery\"?", o: ["ابن سينا", "الزهراوي", "الرازي", "ابن رشد"], c: 1, d: 'HARD' },
  { ar: "ما العلم الذي اشتُق اسمه من كتاب الخوارزمي «الجبر والمقابلة»؟", en: "Science named after al-Khwarizmi's book?", o: ["الهندسة", "الجبر", "الحساب", "المثلثات"], c: 1 },
  { ar: "من العالم الذي اشتُقت كلمة «خوارزمية» من اسمه؟", en: "Scholar whose name gave us \"algorithm\"?", o: ["البيروني", "الخوارزمي", "الكندي", "ابن سينا"], c: 1, d: 'HARD' },
  { ar: "من الرحالة المسلم الشهير الذي جاب العالم وكتب رحلته؟", en: "Famous Muslim traveler who toured the world?", o: ["ابن خلدون", "ابن بطوطة", "الإدريسي", "ابن جبير"], c: 1 },
  { ar: "من العالم المسلم الذي رسم خرائط دقيقة للعالم لملك صقلية؟", en: "Muslim who mapped the world for Sicily's king?", o: ["البيروني", "الإدريسي", "المسعودي", "ياقوت"], c: 1, d: 'HARD' },
  { ar: "من العالم المسلم الملقب بـ«المعلم الثاني» بعد أرسطو؟", en: "Muslim called \"the Second Teacher\" after Aristotle?", o: ["الكندي", "الفارابي", "ابن رشد", "ابن سينا"], c: 1, d: 'HARD' },
  { ar: "من الفيلسوف المسلم الذي عُرف في أوروبا باسم «أفيروس»؟", en: "Muslim philosopher known in Europe as \"Averroes\"?", o: ["ابن سينا", "ابن رشد", "الغزالي", "الفارابي"], c: 1, d: 'HARD' },
  { ar: "من العالم المسلم الذي قاس محيط الأرض وبرع في الفلك؟", en: "Muslim who measured Earth's circumference?", o: ["الخوارزمي", "البيروني", "الفرغاني", "ابن يونس"], c: 1, d: 'HARD' },
  { ar: "ما المؤسسة العلمية الشهيرة في بغداد لترجمة العلوم؟", en: "Famous Baghdad institute for translating sciences?", o: ["دار العلوم", "بيت الحكمة", "المكتبة الظاهرية", "الأزهر"], c: 1, d: 'HARD' },
  { ar: "في أي عصر ازدهرت العلوم عند المسلمين؟", en: "Golden age of Muslim science fell in which era?", o: ["الأموي", "العباسي", "العثماني", "الأندلسي"], c: 1, d: 'HARD' },
  { ar: "ما الرقم الذي طوّره المسلمون وأدخلوه في الرياضيات؟", en: "Number Muslims developed in mathematics?", o: ["الواحد", "الصفر", "العشرة", "المئة"], c: 1 },
  { ar: "ما الآلة الفلكية التي طوّرها المسلمون لتحديد المواقع والوقت؟", en: "Astronomical tool Muslims advanced for position & time?", o: ["البوصلة", "الأسطرلاب", "الساعة الرملية", "الميزان"], c: 1, d: 'HARD' },
  { ar: "من أول فيلسوف في الإسلام ولُقّب بـ«فيلسوف العرب»؟", en: "First philosopher of Islam, \"Philosopher of the Arabs\"?", o: ["الفارابي", "الكندي", "ابن رشد", "ابن سينا"], c: 1, d: 'HARD' },
  { ar: "من أنشأ جامعة القرويين أقدم جامعة قائمة في العالم؟", en: "Founder of al-Qarawiyyin, the oldest existing university?", o: ["زبيدة", "فاطمة الفهري", "الخنساء", "رابعة"], c: 1, d: 'HARD' },
  { ar: "في أي مدينة مغربية تقع جامعة القرويين؟", en: "Moroccan city of al-Qarawiyyin University?", o: ["الرباط", "فاس", "مراكش", "طنجة"], c: 1, d: 'HARD' },
  { ar: "من العالم الذي ألّف «معجم البلدان» في الجغرافيا؟", en: "Author of the geographic dictionary \"Mu'jam al-Buldan\"?", o: ["الإدريسي", "ياقوت الحموي", "المسعودي", "ابن بطوطة"], c: 1, d: 'HARD' },
  { ar: "في أي مجال أبدع جابر بن حيان؟", en: "Field of Jabir ibn Hayyan's genius?", o: ["الفلك", "الكيمياء", "الطب", "الجغرافيا"], c: 1 },
  { ar: "من المؤرخ والرحالة المسلم الذي ألّف «مروج الذهب»؟", en: "Muslim historian who wrote \"Meadows of Gold\"?", o: ["ابن خلدون", "المسعودي", "الطبري", "ابن بطوطة"], c: 1, d: 'HARD' },
  { ar: "ما اللغة التي كُتبت بها معظم المؤلفات العلمية في العصر الذهبي؟", en: "Main language of Golden-Age scientific works?", o: ["الفارسية", "العربية", "اللاتينية", "التركية"], c: 1 },
  { ar: "من الطبيب المسلم الذي فرّق بين الجدري والحصبة لأول مرة؟", en: "Muslim physician who distinguished smallpox from measles?", o: ["ابن سينا", "الرازي", "الزهراوي", "ابن النفيس"], c: 1, d: 'HARD' },
  { ar: "ما الكتاب الذي أرسى فيه ابن خلدون علم العمران البشري؟", en: "Ibn Khaldun's foundational work on society?", o: ["الحاوي", "المقدمة", "القانون", "المناظر"], c: 1, d: 'HARD' },
  { ar: "من العالم الذي أثبت أن الضوء يدخل العين ولا يخرج منها؟", en: "Scholar who showed light enters the eye?", o: ["الكندي", "ابن الهيثم", "البيروني", "الفارابي"], c: 1, d: 'HARD' },
  { ar: "ما العلم الذي يدرس النجوم والأجرام وبرع فيه المسلمون؟", en: "Science of stars that Muslims excelled in?", o: ["الكيمياء", "الفلك", "النبات", "الجغرافيا"], c: 1, d: 'EASY' },
  { ar: "من العالم المسلم الذي وضع جداول فلكية دقيقة وبرع في المثلثات؟", en: "Muslim astronomer of precise tables and trigonometry?", o: ["البيروني", "البتاني", "الفرغاني", "الخوارزمي"], c: 1, d: 'HARD' },
  { ar: "ما الإسهام الأبرز للمسلمين في الرياضيات نُقل لأوروبا؟", en: "Muslim math contribution adopted by Europe?", o: ["الكسور فقط", "الأرقام العربية", "الآلة الحاسبة", "الكمبيوتر"], c: 1 },
  { ar: "أين كانت أهم مراكز العلم في الأندلس؟", en: "Main center of learning in Andalusia?", o: ["غرناطة", "قرطبة", "إشبيلية", "طليطلة"], c: 1, d: 'HARD' },
  { ar: "ما الحقبة التي تُعرف بـ«العصر الذهبي للإسلام» علمياً؟", en: "Period known as the \"Islamic Golden Age\"?", o: ["القرن الأول الهجري", "بين القرنين 8 و13 الميلادي", "القرن العشرين", "ما قبل الإسلام"], c: 1, d: 'HARD' },
  { ar: "في أي مجال برع ابن سينا إلى جانب الطب؟", en: "Ibn Sina's other field besides medicine?", o: ["الزراعة", "الفلسفة", "التجارة", "الفن"], c: 1 },
  { ar: "من العالم المسلم الذي يُعد من أوائل من فصل الصيدلة عن الطب؟", en: "Scholar who helped separate pharmacy from medicine?", o: ["ابن سينا", "الرازي", "الزهراوي", "البيروني"], c: 1, d: 'HARD' },
  { ar: "ما العلم الذي يُنسب للخوارزمي إلى جانب الجبر؟", en: "Field credited to al-Khwarizmi besides algebra?", o: ["علم الفلك فقط", "علم الحساب (الخوارزميات)", "الطب", "الجغرافيا"], c: 1, d: 'HARD' },
  { ar: "من العالم المسلم رائد علم الكيمياء وتجارب التقطير؟", en: "Pioneer of chemistry & distillation experiments?", o: ["الرازي", "جابر بن حيان", "الكندي", "البيروني"], c: 1, d: 'HARD' },
  { ar: "من يُلقب بـ«أبو الطب» من علماء المسلمين؟", en: "Muslim \"Father of Medicine\"?", o: ["ابن سينا", "الخوارزمي", "ابن الهيثم", "جابر بن حيان"], c: 0 },
  { ar: "من العالم المسلم المؤسس لعلم الجبر؟", en: "Founder of algebra?", o: ["الخوارزمي", "البيروني", "ابن رشد", "الرازي"], c: 0, d: 'HARD' },
  { ar: "من رائد علم البصريات صاحب «كتاب المناظر»؟", en: "Pioneer of optics, author of \"Book of Optics\"?", o: ["ابن الهيثم", "ابن سينا", "الكندي", "الفارابي"], c: 0 },
  { ar: "من يُعد رائد علم الكيمياء عند المسلمين؟", en: "Pioneer of chemistry among Muslims?", o: ["جابر بن حيان", "الخوارزمي", "ابن خلدون", "الإدريسي"], c: 0, d: 'HARD' },
  { ar: "من العالم الذي ألّف «المقدمة» وأرسى علم الاجتماع؟", en: "Author of \"The Muqaddimah\", founder of sociology?", o: ["ابن بطوطة", "ابن خلدون", "الإدريسي", "الرازي"], c: 1 },
  { ar: "ما العلم الذي يُنسب لابن الهيثم؟", en: "Ibn al-Haytham's field?", o: ["الجبر", "البصريات", "الكيمياء", "الجغرافيا"], c: 1, d: 'HARD' },
];
