/** السيرة النبوية — The Prophet's Biography. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const seerah: BankQuestion[] = [
  { ar: "في أي مدينة وُلد النبي محمد ﷺ؟", en: "Birthplace of the Prophet ﷺ?", o: ["المدينة", "مكة", "الطائف", "جدة"], c: 1, d: 'EASY' },
  { ar: "ما اسم والدة النبي ﷺ؟", en: "The Prophet's mother?", o: ["آمنة بنت وهب", "حليمة السعدية", "خديجة", "فاطمة"], c: 0 },
  { ar: "من أول من آمن من الرجال؟", en: "First man to embrace Islam?", o: ["عمر", "أبو بكر", "عثمان", "علي"], c: 1, d: 'HARD' },
  { ar: "كم كان عمر النبي ﷺ عند البعثة؟", en: "Age at prophethood?", o: ["30", "40", "50", "25"], c: 1 },
  { ar: "ما اسم الغار الذي نزل فيه الوحي أول مرة؟", en: "Cave of first revelation?", o: ["ثور", "حراء", "الكهف", "الأرقم"], c: 1 },
  { ar: "ما اسم والد النبي ﷺ؟", en: "The Prophet's father?", o: ["عبدالمطلب", "عبدالله", "أبو طالب", "الزبير"], c: 1 },
  { ar: "ما اسم جد النبي ﷺ الذي كفله بعد وفاة أمه؟", en: "Grandfather who raised the Prophet ﷺ?", o: ["أبو طالب", "عبدالمطلب", "هاشم", "عبد مناف"], c: 1 },
  { ar: "ما اسم عم النبي ﷺ الذي كفله ونصره؟", en: "Uncle who protected the Prophet ﷺ?", o: ["حمزة", "أبو طالب", "العباس", "أبو لهب"], c: 1 },
  { ar: "ما اسم مرضعة النبي ﷺ في البادية؟", en: "The Prophet's wet-nurse?", o: ["آمنة", "حليمة السعدية", "ثويبة", "بركة"], c: 1 },
  { ar: "كم كان عمر النبي ﷺ عند الهجرة؟", en: "Prophet's age at the Hijrah?", o: ["40", "50", "53", "60"], c: 2, d: 'HARD' },
  { ar: "كم كان عمر النبي ﷺ عند وفاته؟", en: "Prophet's age at death?", o: ["60", "63", "65", "70"], c: 1 },
  { ar: "في أي عام وُلد النبي ﷺ؟", en: "Year of the Prophet's birth?", o: ["عام الحزن", "عام الفيل", "عام الوفود", "عام الرمادة"], c: 1 },
  { ar: "ما العام الذي تُوفيت فيه خديجة وأبو طالب؟", en: "Year Khadijah and Abu Talib died?", o: ["عام الفيل", "عام الحزن", "عام الوفود", "عام الفتح"], c: 1, d: 'HARD' },
  { ar: "من رافق النبي ﷺ في هجرته إلى المدينة؟", en: "Who accompanied the Prophet ﷺ on the Hijrah?", o: ["عمر", "أبو بكر الصديق", "علي", "عثمان"], c: 1 },
  { ar: "في أي غار اختبأ النبي ﷺ وأبو بكر أثناء الهجرة؟", en: "Cave where they hid during the Hijrah?", o: ["حراء", "ثور", "الكهف", "الأرقم"], c: 1 },
  { ar: "ما أول معركة كبرى خاضها المسلمون؟", en: "First major Muslim battle?", o: ["أحد", "بدر", "الخندق", "حنين"], c: 1 },
  { ar: "في أي غزوة استُشهد حمزة عم النبي ﷺ؟", en: "Battle where Hamza was martyred?", o: ["بدر", "أحد", "الخندق", "خيبر"], c: 1, d: 'HARD' },
  { ar: "ما الغزوة التي حُفر فيها الخندق؟", en: "Battle in which a trench was dug?", o: ["بدر", "أحد", "الخندق", "تبوك"], c: 2 },
  { ar: "ما اسم الصلح الذي عُقد بين النبي ﷺ وقريش؟", en: "Treaty between the Prophet ﷺ and Quraysh?", o: ["صلح الحديبية", "صلح الطائف", "بيعة العقبة", "صلح خيبر"], c: 0, d: 'HARD' },
  { ar: "ما اسم آخر حجة حجها النبي ﷺ؟", en: "The Prophet's final pilgrimage?", o: ["حجة الإسلام", "حجة الوداع", "العمرة", "حجة الفتح"], c: 1 },
  { ar: "ما اسم الناقة التي ركبها النبي ﷺ في الهجرة؟", en: "The Prophet's camel during the Hijrah?", o: ["البراق", "القصواء", "العضباء", "الجدعاء"], c: 1, d: 'HARD' },
  { ar: "ما اسم الدابة التي عُرج بها النبي ﷺ ليلة الإسراء؟", en: "Mount of the Night Journey?", o: ["القصواء", "البراق", "العضباء", "الصافنات"], c: 1, d: 'HARD' },
  { ar: "إلى أي مسجد كان الإسراء بالنبي ﷺ؟", en: "Destination mosque of the Night Journey?", o: ["الحرام", "الأقصى", "قباء", "النبوي"], c: 1 },
  { ar: "من أصغر بنات النبي ﷺ؟", en: "The Prophet's youngest daughter?", o: ["زينب", "رقية", "أم كلثوم", "فاطمة"], c: 3, d: 'HARD' },
  { ar: "ما اسم ابن النبي ﷺ من مارية القبطية؟", en: "The Prophet's son from Maria al-Qibtiyya?", o: ["القاسم", "إبراهيم", "الطيب", "الطاهر"], c: 1, d: 'HARD' },
  { ar: "من المؤذن الأول للنبي ﷺ؟", en: "The Prophet's first muezzin?", o: ["زيد", "بلال بن رباح", "أبو هريرة", "عمار"], c: 1 },
  { ar: "ما أول مسجد بُني في الإسلام؟", en: "First mosque built in Islam?", o: ["النبوي", "قباء", "الحرام", "الأقصى"], c: 1, d: 'HARD' },
  { ar: "في أي مدينة تُوفي النبي ﷺ ودُفن؟", en: "City where the Prophet ﷺ died and was buried?", o: ["مكة", "المدينة المنورة", "الطائف", "خيبر"], c: 1 },
  { ar: "كم سنة دامت الدعوة في مكة قبل الهجرة؟", en: "Years of the call in Mecca before the Hijrah?", o: ["10", "13", "20", "5"], c: 1, d: 'HARD' },
  { ar: "كم سنة عاش النبي ﷺ في المدينة بعد الهجرة؟", en: "Years the Prophet ﷺ lived in Medina?", o: ["5", "8", "10", "13"], c: 2, d: 'HARD' },
  { ar: "من القائد المشرك الذي قُتل في غزوة بدر؟", en: "Polytheist leader killed at Badr?", o: ["أبو سفيان", "أبو جهل", "أبو لهب", "الوليد"], c: 1, d: 'HARD' },
  { ar: "ما البيعة التي مهّدت لهجرة النبي ﷺ إلى المدينة؟", en: "Pledge that paved the way for the Hijrah?", o: ["بيعة الرضوان", "بيعة العقبة", "بيعة الفتح", "بيعة الشجرة"], c: 1, d: 'HARD' },
  { ar: "ما آخر غزوة قادها النبي ﷺ بنفسه؟", en: "Last expedition the Prophet ﷺ led himself?", o: ["حنين", "تبوك", "خيبر", "مؤتة"], c: 1, d: 'HARD' },
  { ar: "في أي معركة استُشهد جعفر بن أبي طالب وزيد بن حارثة؟", en: "Battle where Ja'far and Zayd were martyred?", o: ["بدر", "مؤتة", "أحد", "خيبر"], c: 1, d: 'HARD' },
  { ar: "من زوجة النبي ﷺ الملقبة بأم المؤمنين وأكثرهن روايةً للحديث؟", en: "Wife who narrated the most hadith?", o: ["خديجة", "عائشة", "حفصة", "سودة"], c: 1 },
  { ar: "ما الحادثة التي شُقّ فيها صدر النبي ﷺ في صغره؟", en: "Incident of the Prophet's chest being opened as a child?", o: ["الإسراء", "شق الصدر", "الفيل", "حلف الفضول"], c: 1, d: 'HARD' },
  { ar: "ما الحلف الذي شارك فيه النبي ﷺ قبل البعثة لنصرة المظلوم؟", en: "Pre-prophethood alliance to aid the oppressed?", o: ["حلف الفضول", "حلف قريش", "حلف العقبة", "حلف بدر"], c: 0, d: 'HARD' },
  { ar: "ما اللقب الذي عُرف به النبي ﷺ قبل البعثة لأمانته؟", en: "The Prophet's pre-prophethood title for honesty?", o: ["الفاروق", "الصادق الأمين", "أبو القاسم", "المصطفى"], c: 1 },
  { ar: "من أول شهيدة في الإسلام؟", en: "First female martyr in Islam?", o: ["خديجة", "سمية بنت خياط", "نسيبة", "أم سلمة"], c: 1, d: 'HARD' },
  { ar: "إلى أي مدينة هاجر النبي ﷺ (كانت تُسمى يثرب)؟", en: "City the Prophet ﷺ migrated to (Yathrib)?", o: ["الطائف", "المدينة", "مكة", "خيبر"], c: 1 },
  { ar: "في أي سنة هجرية فُتحت مكة المكرمة؟", en: "Hijri year of the conquest of Mecca?", o: ["6هـ", "8هـ", "10هـ", "2هـ"], c: 1, d: 'HARD' },
  { ar: "أين أُلقيت خطبة الوداع؟", en: "Where was the Farewell Sermon delivered?", o: ["منى", "عرفة", "مزدلفة", "مكة"], c: 1, d: 'HARD' },
  { ar: "من أول طفل وُلد للمهاجرين في المدينة؟", en: "First child born to the Muhajirun in Medina?", o: ["الحسن", "عبدالله بن الزبير", "أنس", "معاذ"], c: 1, d: 'HARD' },
  { ar: "ما اسم والدة النبي ﷺ؟", en: "The Prophet's mother?", o: ["آمنة بنت وهب", "حليمة السعدية", "خديجة", "فاطمة"], c: 0 },
  { ar: "كم كان عمر النبي ﷺ عند نزول الوحي عليه؟", en: "The Prophet's age at the first revelation?", o: ["30", "40", "50", "25"], c: 1 },
];
