/** حقائق غريبة — Weird Facts. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const weirdFacts: BankQuestion[] = [
  { ar: "أي حيوان قلبه أكبر من دماغه بكثير ولا يستطيع القفز؟", en: "Animal that can't jump?", o: ["الأرنب", "الفيل", "القط", "الحصان"], c: 1, d: 'MEDIUM' },
  { ar: "ما العضو الوحيد الذي لا يتعب أبداً؟", en: "Organ that never tires?", o: ["القلب", "العين", "الرئة", "اليد"], c: 0 },
  { ar: "ما الطعام الذي لا يفسد أبداً تقريباً؟", en: "Food that (almost) never spoils?", o: ["الحليب", "العسل", "الخبز", "اللحم"], c: 1 },
  { ar: "ما العضو الذي ينمو طوال حياة الإنسان؟", en: "Body part that keeps growing through life?", o: ["القلب", "الأنف والأذنان", "الكبد", "المخ"], c: 1, d: 'HARD' },
  { ar: "ما السائل الوحيد الذي يتمدد عند التجمد؟", en: "Liquid that expands when frozen?", o: ["الزيت", "الماء", "الكحول", "الزئبق"], c: 1, d: 'MEDIUM' },
  { ar: "ما الطائر الوحيد الذي يستطيع الطيران للخلف؟", en: "Only bird that can fly backward?", o: ["النسر", "الطنان", "البطريق", "النعامة"], c: 1, d: 'MEDIUM' },
  { ar: "ما الذي يجعل لون السماء أزرق؟", en: "Why is the sky blue?", o: ["البحر", "تشتت ضوء الشمس", "الغيوم", "الفضاء"], c: 1, d: 'HARD' },
  { ar: "ما الكائن الذي يستطيع إعادة نمو أطرافه المقطوعة؟", en: "Creature that regrows lost limbs?", o: ["السمكة", "نجم البحر", "الطائر", "الفأر"], c: 1, d: 'HARD' },
  { ar: "كم عدد التذوقات الأساسية التي يميّزها اللسان؟", en: "Number of basic tastes the tongue detects?", o: ["ثلاثة", "أربعة", "خمسة", "اثنان"], c: 2, d: 'MEDIUM' },
  { ar: "ما الحيوان الذي يرى الأشعة فوق البنفسجية؟", en: "Animal that sees ultraviolet light?", o: ["القط", "النحل", "الكلب", "الحصان"], c: 1, d: 'MEDIUM' },
  { ar: "ما الفاكهة التي تطفو على الماء لاحتوائها على هواء؟", en: "Fruit that floats because it contains air?", o: ["الموز", "التفاح", "العنب", "الفراولة"], c: 1, d: 'MEDIUM' },
  { ar: "ما الكائن الذي يستطيع البقاء حياً أياماً بلا رأس؟", en: "Creature that survives days without a head?", o: ["النحلة", "الصرصور", "الفراشة", "النملة"], c: 1, d: 'MEDIUM' },
  { ar: "ما الحيوان الذي بصمة أنفه فريدة مثل بصمة الإنسان؟", en: "Animal with a unique nose print?", o: ["القط", "الكلب", "الحصان", "البقرة"], c: 1, d: 'MEDIUM' },
  { ar: "ما العضو الداخلي الذي يستطيع تجديد نفسه إذا تضرر جزء منه؟", en: "Internal organ that can regenerate?", o: ["القلب", "الكبد", "الرئة", "الكلية"], c: 1, d: 'HARD' },
  { ar: "ما الكوكب الأكثر حرارة رغم أنه ليس الأقرب للشمس؟", en: "Hottest planet though not the closest to the Sun?", o: ["عطارد", "الزهرة", "المريخ", "المشتري"], c: 1, d: 'MEDIUM' },
  { ar: "ما الحيوان الذي ينام بنصف دماغ ويبقى نصفه مستيقظاً؟", en: "Animal that sleeps with half its brain awake?", o: ["القط", "الدلفين", "الكلب", "الحصان"], c: 1, d: 'MEDIUM' },
  { ar: "ما عدد الأذرع لنجم البحر عادةً؟", en: "Usual number of arms on a starfish?", o: ["ثلاثة", "خمسة", "ثمانية", "عشرة"], c: 1 },
  { ar: "ما المادة التي تشكّل النسبة الأكبر من جسم الإنسان؟", en: "Substance making up most of the body?", o: ["الدهون", "الماء", "العظام", "البروتين"], c: 1 },
  { ar: "كم عدد عظام جسم الطفل حديث الولادة تقريباً؟", en: "Approx. bones in a newborn?", o: ["100", "206", "300", "500"], c: 2, d: 'MEDIUM' },
  { ar: "ما الحشرة الأكثر عدداً على الأرض تقريباً؟", en: "Most numerous insect on Earth?", o: ["الذباب", "النمل", "النحل", "الفراش"], c: 1, d: 'HARD' },
  { ar: "ما الطعام الذي لا يفسد تقريباً مع مرور الزمن؟", en: "Food that (almost) never spoils?", o: ["الحليب", "العسل", "الخبز", "اللحم"], c: 1 },
  { ar: "ما الحيوان الذي لا يستطيع القفز إطلاقاً؟", en: "Animal that cannot jump at all?", o: ["الأرنب", "الفيل", "القط", "الحصان"], c: 1, d: 'HARD' },
  { ar: "ما اللون الأكثر حساسية لدى العين البشرية؟", en: "Colour the human eye is most sensitive to?", o: ["الأحمر", "الأخضر", "الأزرق", "الأصفر"], c: 1, d: 'HARD' },
  { ar: "ما أسرع عضلة في جسم الإنسان؟", en: "Fastest muscle in the human body?", o: ["القلب", "عضلات العين", "اليد", "الساق"], c: 1, d: 'HARD' },
  { ar: "ما الحيوان الأطول عمراً بين المعروفة من الزواحف؟", en: "Long-lived reptile?", o: ["الكلب", "السلحفاة", "الأسد", "الأرنب"], c: 1 },
  { ar: "ما المسافة التي يقطعها الضوء في ثانية واحدة تقريباً؟", en: "Distance light travels in one second?", o: ["1000 كم", "300 ألف كم", "مليون كم", "100 كم"], c: 1, d: 'MEDIUM' },
  { ar: "ما الذي يجعل القطط ترى في الإضاءة الخافتة أفضل من الإنسان؟", en: "Why cats see better in low light?", o: ["لا فرق", "بنية عيونها الخاصة", "لأنها أكبر", "بسبب الأذنين"], c: 1, d: 'MEDIUM' },
  { ar: "ما العدد التقريبي للخلايا العصبية في دماغ الإنسان؟", en: "Approx. neurons in the human brain?", o: ["ألف", "ملايين", "مليارات", "مئة"], c: 2, d: 'MEDIUM' },
  { ar: "ما الطائر الذي لا يطير ويضع أكبر بيضة؟", en: "Flightless bird laying the largest egg?", o: ["البطريق", "النعامة", "الدجاج", "البطة"], c: 1, d: 'EASY' },
  { ar: "ما نسبة الطاقة التي يستهلكها الدماغ من طاقة الجسم تقريباً؟", en: "Share of body energy used by the brain?", o: ["2%", "20%", "50%", "80%"], c: 1, d: 'MEDIUM' },
  { ar: "ما الذي يحدث لحجم الماء عند تجمده؟", en: "What happens to water's volume when it freezes?", o: ["ينقص", "يزداد", "يبقى ثابتاً", "يختفي"], c: 1, d: 'MEDIUM' },
  { ar: "ما اللون الذي ينتج عن انعكاس كل ألوان الضوء؟", en: "Colour reflecting all light wavelengths?", o: ["الأسود", "الأبيض", "الأحمر", "الأزرق"], c: 1, d: 'MEDIUM' },
  { ar: "ما العضو الذي يعمل بلا توقف حتى أثناء النوم؟", en: "Organ that works nonstop even in sleep?", o: ["اليد", "القلب", "العين", "الساق"], c: 1, d: 'EASY' },
  { ar: "كم قلباً لدى الأخطبوط؟", en: "How many hearts does an octopus have?", o: ["1", "2", "3", "4"], c: 2, d: 'MEDIUM' },
  { ar: "ما العضو الذي لا يتعب أبداً ويعمل طوال العمر؟", en: "Organ that never tires?", o: ["القلب", "العين", "الرئة", "اليد"], c: 0 },
];
