/** عجائب العالم — World Wonders. Target: 500 questions. */
import type { BankQuestion } from './types.js';

export const worldWonders: BankQuestion[] = [
  { ar: "في أي دولة تقع مدينة «بترا» الوردية؟", en: "Country of Petra?", o: ["الأردن", "مصر", "لبنان", "سوريا"], c: 0 },
  { ar: "في أي دولة يقع «الكولوسيوم»؟", en: "Country of the Colosseum?", o: ["اليونان", "إيطاليا", "إسبانيا", "فرنسا"], c: 1 },
  { ar: "في أي دولة يقع تمثال «المسيح الفادي»؟", en: "Country of Christ the Redeemer?", o: ["الأرجنتين", "البرازيل", "المكسيك", "تشيلي"], c: 1, d: 'MEDIUM' },
  { ar: "في أي دولة تقع مدينة «ماتشو بيتشو»؟", en: "Country of Machu Picchu?", o: ["المكسيك", "بيرو", "تشيلي", "كولومبيا"], c: 1, d: 'MEDIUM' },
  { ar: "في أي دولة يقع هرم «تشيتشن إيتزا» (المايا)؟", en: "Country of Chichen Itza?", o: ["بيرو", "المكسيك", "غواتيمالا", "البرازيل"], c: 1, d: 'HARD' },
  { ar: "أين كانت «حدائق بابل المعلقة»؟", en: "Location of the Hanging Gardens of Babylon?", o: ["مصر", "العراق", "اليونان", "إيران"], c: 1, d: 'MEDIUM' },
  { ar: "أين كانت «منارة الإسكندرية»؟", en: "Location of the Lighthouse of Alexandria?", o: ["اليونان", "مصر", "إيطاليا", "تركيا"], c: 1, d: 'MEDIUM' },
  { ar: "في أي دولة يقع برج إيفل؟", en: "Country of the Eiffel Tower?", o: ["إيطاليا", "فرنسا", "بريطانيا", "إسبانيا"], c: 1, d: 'EASY' },
  { ar: "في أي دولة يقع برج بيزا المائل؟", en: "Country of the Leaning Tower of Pisa?", o: ["إسبانيا", "إيطاليا", "اليونان", "فرنسا"], c: 1 },
  { ar: "في أي دولة يقع برج خليفة أطول مبنى في العالم؟", en: "Country of the Burj Khalifa?", o: ["السعودية", "الإمارات", "قطر", "الكويت"], c: 1, d: 'EASY' },
  { ar: "في أي دولة تقع «الكعبة المشرفة»؟", en: "Country of the Holy Kaaba?", o: ["الأردن", "السعودية", "مصر", "العراق"], c: 1, d: 'EASY' },
  { ar: "في أي دولة تقع «ساعة بيغ بن»؟", en: "Country of Big Ben?", o: ["فرنسا", "بريطانيا", "ألمانيا", "أمريكا"], c: 1 },
  { ar: "في أي دولة تقع «دار أوبرا سيدني» ذات الأشرعة؟", en: "Country of the sail-shaped Sydney Opera House?", o: ["نيوزيلندا", "أستراليا", "أمريكا", "بريطانيا"], c: 1, d: 'HARD' },
  { ar: "في أي دولة يقع «الجامع الأزرق»؟", en: "Country of the Blue Mosque?", o: ["مصر", "تركيا", "إيران", "المغرب"], c: 1, d: 'HARD' },
  { ar: "في أي دولة يقع «الكرملين» والساحة الحمراء؟", en: "Country of the Kremlin and Red Square?", o: ["أوكرانيا", "روسيا", "بولندا", "ألمانيا"], c: 1, d: 'MEDIUM' },
  { ar: "بين أي دولتين تقع «شلالات نياغرا»؟", en: "Niagara Falls lies between which countries?", o: ["البرازيل والأرجنتين", "أمريكا وكندا", "فرنسا وألمانيا", "الهند ونيبال"], c: 1, d: 'HARD' },
  { ar: "في أي قارة يقع «جبل كليمنجارو»؟", en: "Continent of Mount Kilimanjaro?", o: ["آسيا", "إفريقيا", "أوروبا", "أمريكا"], c: 1, d: 'MEDIUM' },
  { ar: "في أي دولة يقع «الحرم النبوي الشريف»؟", en: "Country of the Prophet's Mosque?", o: ["الأردن", "السعودية", "مصر", "فلسطين"], c: 1, d: 'EASY' },
  { ar: "في أي مدينة يقع «المسجد الأقصى»؟", en: "City of Al-Aqsa Mosque?", o: ["عمّان", "القدس", "دمشق", "بيروت"], c: 1 },
  { ar: "في أي دولة يقع معبد «أنغكور وات» أكبر معبد ديني؟", en: "Country of Angkor Wat?", o: ["تايلاند", "كمبوديا", "فيتنام", "الهند"], c: 1, d: 'MEDIUM' },
  { ar: "في أي دولة يقع نُصب «ستونهنج» الحجري الغامض؟", en: "Country of Stonehenge?", o: ["أيرلندا", "بريطانيا", "فرنسا", "ألمانيا"], c: 1, d: 'MEDIUM' },
  { ar: "ما المبنى الأطول في العالم حالياً؟", en: "Tallest building in the world today?", o: ["برج المملكة", "برج خليفة", "برج شنغهاي", "إمباير ستيت"], c: 1 },
  { ar: "ما المتحف الفرنسي الأشهر الذي يضم لوحة الموناليزا؟", en: "French museum holding the Mona Lisa?", o: ["أورسيه", "اللوفر", "بومبيدو", "فرساي"], c: 1, d: 'HARD' },
  { ar: "كم عدد عجائب الدنيا السبع القديمة؟", en: "Number of the ancient wonders of the world?", o: ["5", "7", "9", "10"], c: 1, d: 'EASY' },
  { ar: "في أي دولة يقع «جسر البوابة الذهبية»؟", en: "Country of the Golden Gate Bridge?", o: ["كندا", "الولايات المتحدة", "بريطانيا", "أستراليا"], c: 1, d: 'MEDIUM' },
  { ar: "في أي دولة تقع الأهرامات الثلاثة الكبرى (خوفو وخفرع ومنقرع)؟", en: "Country of the three great pyramids?", o: ["السودان", "مصر", "المكسيك", "العراق"], c: 1 },
  { ar: "في أي دولة يقع «برج المملكة» ومركز الملك عبدالله المالي؟", en: "Country of the Kingdom Centre tower?", o: ["الإمارات", "السعودية", "قطر", "الكويت"], c: 1, d: 'HARD' },
  { ar: "أين كان «تمثال رودس» العملاق من عجائب الدنيا؟", en: "Location of the Colossus of Rhodes?", o: ["مصر", "اليونان", "إيطاليا", "تركيا"], c: 1, d: 'HARD' },
  { ar: "في أي دولة يقع «الحرم المكي»؟", en: "Country of the Grand Mosque of Mecca?", o: ["الأردن", "السعودية", "مصر", "العراق"], c: 1, d: 'EASY' },
  { ar: "في أي دولة تقع «جزر المالديف» السياحية؟", en: "Ocean region of the Maldives?", o: ["الكاريبي", "المحيط الهندي", "المتوسط", "الأطلسي"], c: 1, d: 'MEDIUM' },
  { ar: "في أي دولة يقع «تاج محل»؟", en: "Country of the Taj Mahal?", o: ["باكستان", "الهند", "إيران", "بنغلاديش"], c: 1 },
  { ar: "ما العجيبة الوحيدة الباقية من عجائب الدنيا السبع القديمة؟", en: "Only surviving ancient wonder?", o: ["حدائق بابل", "أهرامات الجيزة", "منارة الإسكندرية", "تمثال رودس"], c: 1, d: 'HARD' },
  { ar: "في أي قارة تقع أهرامات الجيزة الشهيرة؟", en: "Continent of the Giza pyramids?", o: ["آسيا", "إفريقيا", "أوروبا", "أمريكا"], c: 1, d: 'EASY' },
];
