/**
 * One-off migration: split the single QUESTION_BANK object into one file per
 * category under prisma/bank/, resolving BANK_ALIASES on the way so each file is
 * named for the category it actually feeds.
 *
 * Reason: the client's brief is 500 questions per category — ~30,000 rows. That does
 * not fit in one editable file. One file per category keeps each bank at a size that
 * can be appended to and reviewed on its own.
 *
 *   pnpm --filter @tahaddi/server exec tsx prisma/splitBank.ts
 *
 * Safe to re-run: it rewrites every bank file from the current in-memory bank.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { QUESTION_BANK, type BankQuestion } from './questionBank.js';
import { CATEGORIES, BANK_ALIASES } from './taxonomy.js';

const OUT = new URL('./bank/', import.meta.url);
mkdirSync(OUT, { recursive: true });

const J = (s: string) => JSON.stringify(s);
const line = (q: BankQuestion) =>
  `  { ar: ${J(q.ar)}, en: ${J(q.en)}, o: [${q.o.map(J).join(', ')}], c: ${q.c}${q.d ? `, d: '${q.d}'` : ''} },`;

/** camelCase identifier for a slug: `football-arab` → `footballArab`. */
const ident = (slug: string) => slug.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

const byCategory = new Map<string, BankQuestion[]>();
for (const c of CATEGORIES) byCategory.set(c.slug, []);
for (const [key, questions] of Object.entries(QUESTION_BANK)) {
  const slug = BANK_ALIASES[key] ?? key;
  const bucket = byCategory.get(slug);
  if (!bucket) {
    console.warn(`  ⚠️  bank key "${key}" → "${slug}" is not a live category — skipped`);
    continue;
  }
  bucket.push(...questions);
}

for (const c of CATEGORIES) {
  const questions = byCategory.get(c.slug)!;
  const body = questions.map(line).join('\n');
  writeFileSync(
    new URL(`./${c.slug}.ts`, OUT),
    `/** ${c.nameAr} — ${c.nameEn}. Target: 500 questions. */\n` +
      `import type { BankQuestion } from './types.js';\n\n` +
      `export const ${ident(c.slug)}: BankQuestion[] = [\n${body}\n];\n`,
    'utf8',
  );
  console.log(`  ✓ bank/${c.slug}.ts — ${questions.length}`);
}

const imports = CATEGORIES.map((c) => `import { ${ident(c.slug)} } from './${c.slug}.js';`).join('\n');
const entries = CATEGORIES.map((c) => `  '${c.slug}': ${ident(c.slug)},`).join('\n');
writeFileSync(
  new URL('./index.ts', OUT),
  `/**\n` +
    ` * The question bank, assembled from one file per category.\n` +
    ` *\n` +
    ` * Keys are category slugs from prisma/taxonomy.ts. To add questions to a category,\n` +
    ` * append to that category's file — never to this index.\n` +
    ` *\n` +
    ` * Generated by prisma/splitBank.ts; the import list is maintained by hand from here on\n` +
    ` * (a new category = a new file + a line below).\n` +
    ` */\n` +
    `import type { BankQuestion } from './types.js';\n${imports}\n\n` +
    `export const QUESTION_BANK: Record<string, BankQuestion[]> = {\n${entries}\n};\n`,
  'utf8',
);
console.log(`\n✅ split ${CATEGORIES.length} categories, ${[...byCategory.values()].reduce((n, q) => n + q.length, 0)} questions`);
